:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= エレクトロニクス・メーカーＡ社の事例

== 与件

A社は、資本金2500万円、売上約12億円のエレクトロニクス・メーカーである。役員5名を除く従業員数は約50名で、そのほとんどが正規社員である。代表取締役は、1970年代後半に同社を立ち上げたA社長である。現在のA社は電気機器開発に特化し、基本的に生産を他社に委託し、販売も信頼できる複数のパートナー企業に委託している、研究開発中心の企業である。この10年間は売上のおよそ6割を、複写機の再生品や複合機内部の部品、複写機用トナーなどの消耗品が占めている。そして、残りの4割を、同社が受託し独自で開発している食肉用のトレーサビリティー装置、業務用LED照明、追尾型太陽光発電システムなど、電子機器の部品から完成品に至る多様で幅広い製品が占めている。

大手コンデンサーメーカーの技術者として経験を積んだ後、農業を主産業とする故郷に戻ったA社長は、近隣に進出していた国内大手電子メーカー向けの特注電子機器メーカーA社を創業した。その後、同社のコアテクノロジーであるセンサー技術が評価されるようになると、主力取引先以外の大手。中堅メーカーとの共同プロジェクトへの参画が増えたこともあって、気象衛星画像データの受信機や、カメラ一体型のイメージセンサーやコントローラーなど高精度の製品開発にも取り組むことになった。もっとも、当時は売上の8割近くを主力取引先向け電子機器製造に依存していた。

しかし、順調に拡大してきた国内大手電子メーカーの特注電子機器事業が、1990年代初頭のバブル経済の崩壊によって急激な事業縮小を迫られると、A社の売上も大幅に落ち込んだ。経営を足元から揺るがされることになったA社は、農産物や加工食品などの検品装置や、発電効率を高める太陽光システムなど、自社技術を応用した様々な新製品開発にチャレンジせざるを得ない状況に追い込まれた。

平成不況が長引く中で、A社は存続をかけて、ニッチ市場に向けた製品を試行錯誤を重ねながら開発し、事業を継続してきた。もちろん開発した製品すべてが市場で受け入れられるわけもなく、継続的に安定した収入源としてA社の事業の柱となる製品を生み出すこともかなわなかった。そうした危機的状況が、A社長の製品開発に対する考え方を一変させることになる。開発した製品を販売した時点で取引が完了する売切り型の事業の限界を打ち破ることを目標にして、新規事業開発に取り組んだのである。それが、複写機関連製品事業である。

大口顧客は事務機器を販売していたフランチャイズ・チェーンであり、2000年代後半のリーマン・ショックに至る回復基調の景気を追い風にしてA社の業績も伸長した。ところが、リーマン・ショックによって急速に市場が縮小し始めると、A社の売上も頭打ちになった。同業者の多くがこの市場から撤退する中で、A社はシェアこそ拡大させたが、もはや、その後の売上の拡大を期待することのできる状況ではなかった。

ところが、A社がこの事業に参入した頃から、情報通信技術の急速な進歩に伴って、事務機器市場が大きく変化してきた。そのことを予測していたからこそ、A社長
は、後進に事業を委ねる条件が整うまで自らが先頭に立って、新規事業や製品の開発にチャレンジし続けているのである。

これまで幾度かの浮き沈みを経験してきた同社であるが、営業職や事務職、人事・経理・総務などの管理業務を兼務している者を加えた約50名の社員のうち、技術者が9割近くを占めている。創業以来変わることなく社員の大半は技術者であるが、売上が数十倍になった今日に至っても従業員数は数倍程度にとどまっている。

従前A社では、電子回路技術部門、精密機械技術部門、ソフトウェア技術部門と専門知識別に部門化されていた。しかし、複写機関連製品事業が先細り傾向になった頃から、製品開発部門、品質管理部門、生産技術部門に編成替えをし、各部門を統括する部門長を役員が兼任した。製品開発部門は、環境エネルギー事業の開発を推進するグループ、法人顧客向けの精密機械を開発するグループ、LED照明関連製品を開発するグループに分けられ、電子回路技術、精密機械技術、ソフトウェア技術などの専門知識を有する技術者をほぼ同数配置した混成チームとした。品質管理部門と生産技術部門には、数名の技術者が配属され、製品開発部門の業務をサポートすると同時に、複数の生産委託先との調整業務を担っている。

絶えず新しい技術を取り込みながら製品領域の拡大を志向してきたA社にとって、人材は重要な経営資源であり、それを支えているのが同社の人事制度である。

その特徴の一つは、戦力である技術者に新卒者を原則採用せず、地元出身のＵターン組やＩターン組の中途採用者だけに絞っていることである。また、賃金は、設立当初から基本的に年功給の割合をできるだけ少なくして、個人業績は年二回の賞与に多く反映させるようにしてきた。近年、いっそう成果部分を重視するようになり、年収ベースで二倍近くの差が生じることもある。それにもかかわらず、A社の離職率が地元の道教他社に比べて低いことは、実力主義がA社の文化として根付いていることの証左である。とはいえ、その一方で家族主義的な面も多く見られる。社員持株制度や社員全員による海外旅行などの福利厚生施策を充実させているし、1990年代半ばには、技術者による申請特許に基づく装置が売れると、それを表彰して売上の1%を報奨金として技術者が受け取ることができる制度を整備し運用している。

このように、A社は、研究開発型企業として、取引先や顧客などの声を反映させていた受け身の製品開発の時代から、時流を先読みし先進的な事業展開を進める一方で、伝統的な家族主義的要素をも取り入れたて成長を実現している企業だといえる。

（平成30年度　中小企業診断士2次筆記試験　事例1　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startwbs

* A社
** 製品開発部門
*** 環境エネルギー事業の開発を推進するグループ
*** 法人顧客向けの精密機械を開発するグループ
*** LED 照明関連製品を開発するグループ
** 品質管理部門
** 生産技術部門

@endwbs
----

=== ビジネスモデル

[plantuml]
----
@startmindmap

* A社
** 内部環境
*** 顧客
**** 顧客セグメント
***** [1990年代以降] 複写機関連製品の需要がある企業（複写機再生品、トナーなど）。
***** [2000年代以降] 食肉業界（トレーサビリティ装置）。
***** [2010年代以降] 太陽光発電システムやLED照明などのニッチ市場で活動する企業。

**** 顧客関係
***** [創業時～1990年代] 主力取引先に依存（国内大手電子メーカー向け特注製品）。
***** [1990年代以降～] 信頼できる複数のパートナー企業を通じた販売委託。
*****[#lightgreen] [2000年代以降] フランチャイズチェーンとして事務機器を販売する大口顧客との密接な取引。

*** 価値
**** 価値提案
***** [創業時～] 高精度なセンサー技術を活用した特注品提供。
***** [1990年代以降] 市場のニッチ需要に応える製品（リサイクル複写機関連製品やトレーサビリティ装置）。
***** [2000年代以降] 環境意識を持つ企業への対応、迅速なニーズへの製品開発。

**** チャネル
***** [創業時～] 主に国内大手電子メーカー向け直接取引。
***** [1990年代以降] 販売：パートナー企業を通じた委託販売。
***** [1990年代以降] 生産：外部企業への委託生産。

*** インフラ
**** 主要活動
***** [創業時～] 高精度センサー技術を基盤とした製品の開発。
***** [1990年代以降] 複写機関連製品の製造・改良、ニッチ市場向け製品開発。
***** [2000年代～] 環境エネルギーや事務機器関連の製品開発の試行錯誤。

**** 主要リソース
***** [創業時～] 創業者の専門知識と高精度センサー技術。
*****[#lightgreen] [1990年代以降] 高い専門性を持つ技術者（従業員の約9割が技術者）。
*****[#lightgreen] [累積的] 長年の開発による技術実績と知見。

**** 主要パートナー
***** [創業時～1990年代] 国内大手電子メーカー（過去の主要取引先）。
***** [1990年代以降] 信頼できる販売パートナー企業。
***** [1990年代以降] 委託生産を担う外部企業。

*** 資金
**** 収益源
***** [1990年代以降] 複写機関連製品の売上（売上全体の6割）。
***** [2000年代以降] 独自開発の製品売上（売上全体の4割）。

**** コスト構造
***** [累積的] 委託生産に伴う外部依存コスト。
***** [累積的] 研究開発費。
***** [累積的] パートナー企業への販売手数料。

left side
** 外部環境
*** 競争
**** [1990年代以降] 同業者の一部は市場から撤退しているが、A社はシェアを拡大中。
****[#red] [累積的] 市場規模縮小により価格競争や需要低迷の影響を受けやすい。

*** 政治・社会・技術
**** [1990年代以降] 情報通信技術（ICT）の急速な進化により事務機器市場が大きく変化。
**** [2000年代以降] 環境問題への配慮によるリサイクル製品の需要増。
****[#lightblue] [2010年代以降] センサー技術の向上と市場での活用の幅の広がり。

*** マクロ経済
**** [1990年代初頭] バブル崩壊による市場縮小。
**** [1990年代～2000年代] 平成不況や2000年代のリーマンショックによる経済情勢の影響。
**** [累積的] 不況下での多角化や収益源の多様化が鍵となった。

*** 市場
**** [1990年代以降] 複写機関連市場は縮小傾向にあるが、一定のニッチ需要が継続。
****[#lightblue] [2000年代以降] 食肉トレーサビリティ市場やLED、太陽光発電など新興ニッチ市場では成長の可能性あり。

@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap

* SWOT
** 内部環境
***[#lightgreen] 強み
***[#yellow] 弱み
left side
** 外部環境
***[#lightblue] 機会
***[#red] 脅威

@endmindmap
----

=== VRIO分析

[plantuml]
----
@startmindmap

* VRIO
** 経済的価値
** 希少性
left side
** 模倣困難性
** 組織能力

@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap

* ドメイン
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように

@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap

* 成長戦略
** 既存市場
*** 市場浸透
*** 商品開発
** 新市場
*** 市場開発
*** 多角化
**** 水平的多角化
**** 垂直型多角化
**** 集中型多角化
**** 集成型多角化

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** ドメイン
right side
** 成長戦略

@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap

* 基本戦略
** コストリーダーシップ
** 差別化
** 集中

@endmindmap
----

==== 競争戦略

[plantuml]
----
@startmindmap

* 競争戦略
** リーダー
*** 市場拡大
*** 同質化
** チャレンジャー
*** 差別化
** ニッチャー
*** 集中
** フォロワー
*** 追随

@endmindmap
----

==== 価値連鎖

[plantuml]
----
@startmindmap

* 価値連鎖
** 主活動
*** 購買物流
*** 製造
*** 出荷物流
*** マーケティング・販売
*** サービス
** 支援活動
*** インフラストラクチャ
*** 人事・労務管理
*** 技術開発
*** 調達活動

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** 基本戦略
** 競争戦略
right side
** 価値連鎖

@endmindmap
----

=== 機能戦略

==== バリューストリーム

[plantuml]
----
@startmindmap

* バリューストリーム
left side
** マーケティング
** 購買
** 製造
** 販売
** 出荷
** サービス
right side
** マーケティング
*** マーケティング戦略
*** 市場調査
** 生産管理
*** 生産計画
*** 生産統制
** 販売管理
*** 販売計画
*** 受注管理
*** 倉庫管理
** 店舗管理
*** 店舗計画
*** 資材管理
*** 衛生管理

@endmindmap
----

==== ケイパビリティマッピング

[plantuml]
----
@startmindmap

* ビジネスケイパビリティマップ
** コア
*** マーケティング
**** マーケティング戦略
*** 生産管理
**** 生産計画
*** 販売管理
**** 販売計画
*** 店舗管理
**** 店舗計画
** 汎用
*** 生産管理
**** 生産統制
*** 販売管理
**** 受注管理
*** 店舗管理
**** 資材管理
** サポート
*** マーケティング
**** 市場調査
*** 販売管理
**** 倉庫管理
*** 店舗管理
**** 衛生管理

@endmindmap
----

==== 組織マップ

==== 情報マップ

==== ビジネスシナリオ

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
** コア
*** マーケティング
**** マーケティング戦略
*** 生産管理
**** 生産計画
*** 販売管理
**** 販売計画
*** 店舗管理
**** 店舗計画
** 汎用
*** 生産管理
**** 生産統制
*** 販売管理
**** 受注管理
*** 店舗管理
**** 資材管理
** サポート
*** マーケティング
**** 市場調査
*** 販売管理
**** 倉庫管理
*** 店舗管理
**** 衛生管理
left side
** マーケティング
*** マーケティング戦略
*** 市場調査
** 生産管理
*** 生産計画
*** 生産統制
** 販売管理
*** 販売計画
*** 受注管理
*** 倉庫管理
** 店舗管理
*** 店舗計画
*** 資材管理
*** 衛生管理

@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* ドメイン

left side
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように

right side

** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== 業務領域(サブドメイン)

==== 中核の業務領域(コアサブドメイン)

==== 一般的な業務領域(汎用サブドメイン)

==== 補完的な業務領域(サポートサブドメイン)

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

