:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 老舗の蔵元A社の事例

== 与件

　A 社は、わが国を代表する観光地として知られる温泉地にある老舗の蔵元である。資本金は2,000 万円、売上は約5 億円で、中小の同業他社と比べて売上が大きい。A 社の軒下には杉玉がぶら下がり壁際に酒樽などが並んではいるものの、店の中に入るとさまざまな土産物が所狭しと並んでいる。中庭のやや燻した感じの石造りの酒蔵だけが、今でも蔵元であることを示している。

　A 社の売上のうち約2 億円は昔ながらの酒造事業によるものであるが、残りの3 億円はレストランと土産物店の売上である。現在、この老舗の当主は、40 代前半の若いA 社長である。A 社の4 名の役員は全て親族であるが、その中で直接A 社のビジネスに関わっているのはA 社長一人だけである。A 社長、従業員40 名（正規社員20 名、非正規社員20 名）、それにA 社の社員ではない杜氏を加えて、実質42 名体制である。

　実は、江戸時代から続く造り酒屋のA 社は、現在のA 社長と全く血縁関係のない旧家によって営まれていた。戦後の最盛期には酒造事業で年間2 億円以上を売り上げていた。しかし、2000 年代になって日本酒の国内消費量が大幅に減少し、A 社の売上高も半分近くに落ち込んでしまった。そこで、旧家の当主には後継者がいなかったこともあって廃業を考えるようになっていた。とはいえ、屋号を絶やすことへの無念さに加えて、長年にわたって勤めてきた10 名の従業員に対する雇用責任から廃業を逡巡していた。近隣の金融機関や取引先、組合関係者にも相談した結果、地元の有力者の協力を仰ぐことを決めた。

　最終的に友好的買収を決断したこの有力者は、飲食業を皮切りに事業をスタートさせ次々と店舗開拓に成功しただけでなく、30 年ほど前には地元の旅館を買収して娘を女将にすると、全国でも有名な高級旅館へと発展させた実業家である。蔵元として老舗の経営権を獲得した際、前の経営者と経営顧問契約を結んだだけでなく、そこで働いていたベテラン従業員10 名も従来どおりの条件で引き継いだ。

　インバウンドブームの前兆期ともいえる当時、日本の文化や伝統に憧れる来訪者にとっても、200 年の年月に裏打ちされた老舗ブランドは魅力的であるし、それが地域の活性化につながっていくといった確信が買収を後押ししたのである。そして、当時首都圏の金融機関に勤めていた孫のA 社長を地元に呼び戻すと、老舗酒造店の立て直しに取り組ませた。

　幼少時から祖父の跡を継ぐことを運命づけられ、自らも違和感なく育ってきたA社長は金融機関を退職し帰郷した。経営実務の師となる祖父の下で、3 年近くに及ぶ修行がスタートした。酒造りは、経営顧問と杜氏、そしてベテランの蔵人たちから学んだ。

　修行の合間を見ながら、敷地全体のリニューアルにも取り組んだ。以前、製品の保管や居住スペースであった建物を土産物店に改装し、また中庭には古民家風の建物を新たに建て地元の高級食材を提供するレストランとした。1 階フロアは個人客向け、2 階の大広間は団体観光客向けである。また、社員の休憩所なども整備した。さらに、リニューアルの数年後には、酒蔵の横の一部を改装して、造りたての日本酒を堪能できる日本酒バーも開店している。

　こうした新規事業開発の一方で、各部門の責任者と共に酒造、レストラン、土産物販売といった異なる事業を統括する体制づくりにも取り組んだ。酒造りは杜氏やベテランの蔵人たちが中心になり、複雑な事務作業や取引先との商売を誰よりも掌握していたベテランの女性事務員が主に担当した。また、A 社長にとって経験のないレストラン経営や売店経営は、祖父に教えを請いながら徐々に仕事を覚えていった。　

　他方、酒造以外の各部門の責任者となる30 代から40 代半ばまでの経験のある人材を正規社員として、またレストランと土産物店の現場スタッフには地元の学生や主婦を非正規社員として採用した。正規社員として採用した中からレストラン事業、土産物販売事業や総務部門の責任者を配置した。その間も、A 社長は酒造りを学びながら、一方でこれらの社員と共に現場で働き、全ての仕事の流れを確認していくと同時に、その能力を見極めることにも努めた。

　レストラン事業と土産物販売事業は責任者たちが手腕を発揮してくれたことに加えて、旅館などグループ企業からの営業支援もあって、インバウンドの追い風に乗って順調に売上を伸ばしていった。レストランのフロアでは、日本の大学を卒業後、この地域の魅力に引かれて長期滞在していたときに応募してきた外国人数名も忙しく働いている。

　そして、現在、A 社長の右腕として重要な役割を果たしているのは、酒の営業担当の責任者として敏腕を発揮してきた、若き執行役員である。ルートセールスを中心とした古い営業のやり方を抜本的に見直し、直販方式の導入によって本業の酒造事業の売上を伸長させた人材であり、杜氏や蔵人と新規事業との橋渡し役としての役割も果たしている。典型的なファミリービジネスの中にあって、血縁関係がないにもかかわらず、A 社長の頼りがいのある参謀として執行役員に抜擢されている。また、総務担当責任者も前任のベテラン女性事務員と2 年ほど共に働いて知識や経験を受け継いだだけでなく、それを整理して情報システム化を進めたことで抜擢された若い女性社員である。

　A 社長は、この10 年、老舗企業のブランドと事業を継いだだけでなく、新規事業を立ち上げ経営の合理化を進めるとともに、優秀な人材を活用して地元経済の活性化にも大いに貢献してきたという自負がある。しかしながら、A 社の人事管理は、伝統的な家族主義的経営や祖父の経験や勘をベースとした前近代的なものであることも否めない。社員の賃金を同業他社よりやや高めに設定しているとはいえ、年功序列型賃金が基本である。近い将来には、自身が総帥となる企業グループ全体のバランスを考えた人事制度の整備が必須であるとA 社長は考えている。

（令和2年度　中小企業診断士2次筆記試験　事例1　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startwbs

* A社
** 酒造事業
** レストラン・土産物販売事業
** 総務部

@endwbs
----

=== ビジネスモデル

[plantuml]
----
@startmindmap

* ビジネスモデル
-- 外部環境
--- 競争(XC)
--- 政治・社会・技術(XS)
----[#red] 2000 年代になって日本酒の国内消費量が大幅に減少
----[#lightblue] インバウンドの追い風
--- マクロ経済(XE)
--- 市場(XM)
** 内部環境
*** 顧客
**** 顧客セグメント(CS)
**** 顧客関係(CR)
*** 価値
**** 価値提案(VP)
***** 売上のうち2 億円は酒造事業
***** 3 億円はレストランと土産物販売
*****[#lightgreen] レストラン事業と土産物販売事業は責任者たちが手腕を発揮してくれたことに加えて、旅館などグループ企業からの営業支援もあって、インバウンドの追い風に乗って順調に売上を伸ばしていった
**** チャネル(CH)
***** 以前、製品の保管や居住スペースであった建物を土産物店に改装し、また中庭には古民家風の建物を新たに建て地元の高級食材を提供するレストランとした。1 階フロアは個人客向け、2 階の大広間は団体観光客向けである。また、社員の休憩所なども整備した。
***** さらに、リニューアルの数年後には、酒蔵の横の一部を改装して、造りたての日本酒を堪能できる日本酒バーも開店している
*** インフラ
**** 主要活動(KA)
***** 酒造りは杜氏やベテランの蔵人たちが中心になり、複雑な事務作業や取引先との商売を誰よりも掌握していたベテランの女性事務員が主に担当した
*****[#yellow] A 社長にとって経験のないレストラン経営や売店経営は、祖父に教えを請いながら徐々に仕事を覚えていった
*****[#lightgreen] ルートセールスを中心とした古い営業のやり方を抜本的に見直し、直販方式の導入によって本業の酒造事業の売上を伸長させた人材であり、杜氏や蔵人と新規事業との橋渡し役としての役割も果たしている
*****[#lightgreen] 総務担当の責任者も前任のベテラン女性事務員と2 年ほど共に働いて知識や経験を受け継いだだけでなく、それを整理して情報システム化を進めたことで抜擢された若い女性社員である
**** 主要リソース(KR)
***** 資本金は2,000 万円
***** この老舗の当主は、40 代前半の若いA 社長である
***** A社の4 名の役員は全て親族であるが、その中で直接A 社のビジネスに関わっているのはA 社長一人だけである
***** A 社長、従業員40 名（正規社員20 名、非正規社員20 名）、それにA 社の社員ではない杜氏を加えて、実質42 名体制である
***** 蔵元として老舗の経営権を獲得した際、前の経営者と経営顧問契約を結んだだけでなく、そこで働いていたベテラン従業員10 名も従来どおりの条件で引き継いだ
*****[#lightgreen] インバウンドブームの前兆期ともいえる当時、日本の文化や伝統に憧れる来訪者にとっても、200 年の年月に裏打ちされた老舗ブランドは魅力的である
***** 当時首都圏の金融機関に勤めていた孫のA 社長を地元に呼び戻すと、老舗酒造店の立て直しに取り組ませた
***** 経営実務の師となる祖父の下で、3 年近くに及ぶ修行がスタートした
***** 酒造りは、経営顧問と杜氏、そしてベテランの蔵人たちから学んだ
***** 各部門の責任者と共に酒造、レストラン、土産物販売といった異なる事業を統括する体制づくりにも取り組んだ
***** 酒造以外の各部門の責任者となる30 代から40 代半ばまでの経験のある人材を正規社員として、またレストランと土産物店の現場スタッフには地元の学生や主婦を非正規社員として採用した
***** 正社員として採用した中からレストラン事業、土産物販売事業や総務部門の責任者を配置した
***** レストランのフロアでは、日本の大学を卒業後、この地域の魅力に引かれて長期滞在していたときに応募してきた外国人数名も忙しく働いている
*****[#lightgreen] 現在、A 社長の右腕として重要な役割を果たしているのは、酒の営業担当の責任者として敏腕を発揮してきた、若き執行役員である
*****[#yellow] A社の人事管理は、伝統的な家族主義的経営や祖父の経験や勘をベースとした前近代的なものであることも否めない
***** 年功序列型賃金が基本である
*****[#orange] 近い将来には、自身が総帥となる企業グループ全体のバランスを考えた人事制度の整備が必須であるとA 社長は考えている
**** 主要パートナー(KP)
*** 資金
**** 収益源(R$)
*****[#lightgreen] 中小の同業他社と比べて売上が大きい
**** コスト構造(C$)

@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap

* SWOT
** 内部環境
***[#lightgreen] 強み
**** 酒造りとレストラン事業、土産物販売事業を統括する体制
**** 正社員やパートナーが専門知識や経験を持つ人材
**** 老舗ブランドの魅力
***[#yellow] 弱み
**** 人事管理が伝統的な家族主義的経営
**** 前近代的な賃金や人事制度
left side
** 外部環境
***[#lightblue] 機会
**** インバウンドの追い風による売上増
**** 日本の文化や伝統に憧れる来訪者の増加
***[#red] 脅威
**** 日本酒の国内消費量減少

@endmindmap
----

=== VRIO分析

[plantuml]
----
@startmindmap

* VRIO
** 経済的価値
*** 老舗のブランド力による集客効果
*** インバウンド対応による売上増
** 希少性
*** 伝統ある酒造りの技術
*** 長い歴史に裏打ちされた老舗ブランド
left side
** 模倣困難性
*** 専門知識を持つ正社員やパートナーの存在
*** 200年の歴史に基づくブランド
**[#orange] 組織能力
*** 経営顧問や杜氏、ベテランの蔵人たちからの学び
*** 酒造、レストラン、土産物販売の統括体制

@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap

* ドメイン
** 企業ドメイン
*** 理念
**** 伝統と革新を融合させた酒造り
*** ビジョン
**** 文化と歴史を守り、次世代に伝える
*** ミッション
**** 高品質な日本酒と食文化の提供
** 事業ドメイン
*** 酒造事業
**** 誰に
***** 日本国内外の日本酒愛好者
**** 何を
***** 高品質な日本酒
****[#orange] どのように
***** 伝統技術を活かした製造
*** レストラン・土産物販売事業
**** 誰に
***** インバウンド観光客
***** 地元住民
**** 何を
***** 地元の高級食材を使った料理
***** 日本酒関連の土産物
****[#orange] どのように
***** 老舗の信頼性を活かした販売
***** 伝統技術と現代的サービスの融合
***** 地元の観光資源を活用した店舗展開
***** 観光資源を活用した店舗展開
***** 現代的サービスの提供

@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap

* 成長戦略
** 既存市場
*** 市場浸透
**** SNSやオンラインマーケティングによる販促強化
**** 顧客ロイヤリティプログラムの導入
*** 商品開発
**** 新しい日本酒ブランドのラインアップ追加
**** 季節限定商品やコラボ商品開発
** 新市場
*** 市場開発
**** 海外市場への進出
**** インバウンド観光客向けのマーケティング強化
*** 多角化
**** 水平的多角化
***** 他のアルコール飲料の製造
**** 垂直型多角化
***** 酒造りの原材料の自社生産
**** 集中型多角化
***** 日本酒を使ったスキンケア製品の開発
**** 集成型多角化
***** ワイナリーやブリュワリーとの提携

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** ドメイン
*** 企業ドメイン
**** 理念
***** 伝統と革新を融合させた酒造り
**** ビジョン
***** 文化と歴史を守り、次世代に伝える
**** ミッション
***** 高品質な日本酒と食文化の提供
*** 事業ドメイン
**** 酒造事業
***** 誰に
****** 日本国内外の日本酒愛好者
***** 何を
****** 高品質な日本酒
*****[#orange] どのように
****** 伝統技術を活かした製造
**** レストラン・土産物販売事業
***** 誰に
****** インバウンド観光客
****** 地元住民
***** 何を
****** 地元の高級食材を使った料理
****** 日本酒関連の土産物
*****[#orange] どのように
****** 老舗の信頼性を活かした販売
****** 伝統技術と現代的サービスの融合
****** 地元の観光資源を活用した店舗展開
****** 観光資源を活用した店舗展開
****** 現代的サービスの提供
right side
** 成長戦略
*** 既存市場
**** 市場浸透
***** SNSやオンラインマーケティングによる販促強化
***** 顧客ロイヤリティプログラムの導入
**** 商品開発
***** 新しい日本酒ブランドのラインアップ追加
***** 季節限定商品やコラボ商品開発
*** 新市場
**** 市場開発
***** 海外市場への進出
***** インバウンド観光客向けのマーケティング強化
**** 多角化
***** 水平的多角化
****** 他のアルコール飲料の製造
***** 垂直型多角化
****** 酒造りの原材料の自社生産
***** 集中型多角化
****** 日本酒を使ったスキンケア製品の開発
***** 集成型多角化
****** ワイナリーやブリュワリーとの提携

@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap

* 基本戦略
** 酒造事業
*** コストリーダーシップ
**** 生産効率の改善によるコスト削減
**** 規模の経済を活かした原材料の大量仕入れ
*** 差別化
**** 高品質な日本酒のブランド確立
**** 伝統技術と現代的なデザインの融合
*** 集中
**** 国内の高付加価値市場への集中
** レストラン・土産物販売事業
*** コストリーダーシップ
**** 効率的な調理と材料の管理によるコスト削減
*** 差別化
**** 地元の高級食材を使用した独自メニューの提供
**** 観光客向けの独自商品開発
*** 集中
**** 観光地での店舗展開による観光客ターゲット

@endmindmap
----

==== 競争戦略

[plantuml]
----
@startmindmap

* 競争戦略
** 酒造事業
*** リーダー
**** 市場拡大
***** 海外市場への進出
***** 新規顧客層の開拓
**** 同質化
***** 他社製品と同等の高品質を維持しつつ、価格競争力を強化
*** チャレンジャー
**** 差別化
***** 独自の酒造技術やブランドストーリーを強調
***** オリジナル商品の開発と提供
*** ニッチャー
**** 集中
***** 高級日本酒の市場に特化
***** 地域限定商品の開発と販売
*** フォロワー
**** 追随
***** 市場トレンドを敏感にキャッチし、迅速に対応
***** 大手企業の成功事例を参考にした商品展開
** レストラン・土産物販売事業
*** リーダー
**** 市場拡大
***** 新店舗の展開
***** 地域の観光資源を活用したマーケティング
**** 同質化
***** 高品質なサービスを維持しつつ、価格競争力を強化
*** チャレンジャー
**** 差別化
***** 地元の高級食材を使用したメニューの提供
***** 観光客向けの独自商品を開発
*** ニッチャー
**** 集中
***** 特定の観光地やイベントに特化した店舗経営
***** 地元の特産品を利用した限定メニューの提供
*** フォロワー
**** 追随
***** 成功している他社のコンセプトを参考にしつつ、自社の強みを活かした商品展開
***** 観光トレンドや季節の変動に合わせた柔軟な対応

@endmindmap
----

==== 価値連鎖

[plantuml]
----
@startmindmap
* 価値連鎖
** 主活動
*** 購買物流
**** 酒造事業
***** サプライチェーンの効率化
***** 品質管理
**** レストラン・土産物販売事業
***** 物流の最適化
***** 原材料の適時調達
***** 在庫管理
***** 新鮮な食材の安定供給
*** 製造
**** 酒造事業
***** 生産量の安定化
***** 専門技術の導入
**** レストラン・土産物販売事業
***** 生産プロセスの効率化
***** 衛生管理
***** 店舗での調理効率
***** 店内衛生
*** 出荷物流
**** 酒造事業
***** 出荷時の品質維持
***** ロジスティクスコスト削減
**** レストラン・土産物販売事業
***** 梱包効率の向上
***** 最適な出荷計画
***** 店舗への迅速な補充
***** 配送経路の最適化
*** マーケティング・販売
**** 酒造事業
***** 地元の認知度向上
***** ブランド構築
**** レストラン・土産物販売事業
***** 市場調査の精度向上
***** 商品差別化
***** 顧客満足度向上
***** 販売促進活動の効果測定
*** サービス
**** 酒造事業
***** 技術サポート
***** アフターケアの強化
**** レストラン・土産物販売事業
***** クレーム対応
***** 保証サービス提供
***** 顧客対応
***** ロイヤルティプログラムの実施
** 支援活動
*** インフラストラクチャ
**** 酒造事業
***** 設備投資
***** インフラ整備
**** レストラン・土産物販売事業
***** 工場の最新化
***** 安全対策
***** 店舗設計
***** ICTの導入
***[#orange] 人事・労務管理
**** 酒造事業
***** 人材育成
***** 労働環境の改善
**** レストラン・土産物販売事業
***** 労働力の確保
***** チームの統制
***** スタッフのトレーニング
***** 勤務シフトの管理
*** 技術開発
**** 酒造事業
***** 新技術の導入
***** R&Dの推進
**** レストラン・土産物販売事業
***** 製品革新
***** 製造技術の向上
***** サービス向上技術
***** 販売支援システム
*** 調達活動
**** 酒造事業
***** 安定したサプライチェーン
***** コスト削減
**** レストラン・土産物販売事業
***** 原材料の多様化
***** 供給リスクの分散
***** 調達プロセスの効率化
***** ベンダー管理
@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** 基本戦略
*** 酒造事業
**** コストリーダーシップ
***** 生産効率の改善によるコスト削減
***** 規模の経済を活かした原材料の大量仕入れ
**** 差別化
***** 高品質な日本酒のブランド確立
***** 伝統技術と現代的なデザインの融合
**** 集中
***** 国内の高付加価値市場への集中
*** レストラン・土産物販売事業
**** コストリーダーシップ
***** 効率的な調理と材料の管理によるコスト削減
**** 差別化
***** 地元の高級食材を使用した独自メニューの提供
***** 観光客向けの独自商品開発
**** 集中
***** 観光地での店舗展開による観光客ターゲット
** 競争戦略
*** 酒造事業
**** リーダー
***** 市場拡大
****** 海外市場への進出
****** 新規顧客層の開拓
***** 同質化
****** 他社製品と同等の高品質を維持しつつ、価格競争力を強化
**** チャレンジャー
***** 差別化
****** 独自の酒造技術やブランドストーリーを強調
****** オリジナル商品の開発と提供
**** ニッチャー
***** 集中
****** 高級日本酒の市場に特化
****** 地域限定商品の開発と販売
**** フォロワー
***** 追随
****** 市場トレンドを敏感にキャッチし、迅速に対応
****** 大手企業の成功事例を参考にした商品展開
*** レストラン・土産物販売事業
**** リーダー
***** 市場拡大
****** 新店舗の展開
****** 地域の観光資源を活用したマーケティング
***** 同質化
****** 高品質なサービスを維持しつつ、価格競争力を強化
**** チャレンジャー
***** 差別化
****** 地元の高級食材を使用したメニューの提供
****** 観光客向けの独自商品を開発
**** ニッチャー
***** 集中
****** 特定の観光地やイベントに特化した店舗経営
****** 地元の特産品を利用した限定メニューの提供
**** フォロワー
***** 追随
****** 成功している他社のコンセプトを参考にしつつ、自社の強みを活かした商品展開
****** 観光トレンドや季節の変動に合わせた柔軟な対応
right side
** 価値連鎖
*** 主活動
**** 購買物流
***** 酒造事業
****** サプライチェーンの効率化
****** 品質管理
***** レストラン・土産物販売事業
****** 物流の最適化
****** 原材料の適時調達
****** 在庫管理
****** 新鮮な食材の安定供給
**** 製造
***** 酒造事業
****** 生産量の安定化
****** 専門技術の導入
***** レストラン・土産物販売事業
****** 生産プロセスの効率化
****** 衛生管理
****** 店舗での調理効率
****** 店内衛生
**** 出荷物流
***** 酒造事業
****** 出荷時の品質維持
****** ロジスティクスコスト削減
***** レストラン・土産物販売事業
****** 梱包効率の向上
****** 最適な出荷計画
****** 店舗への迅速な補充
****** 配送経路の最適化
**** マーケティング・販売
***** 酒造事業
****** 地元の認知度向上
****** ブランド構築
***** レストラン・土産物販売事業
****** 市場調査の精度向上
****** 商品差別化
****** 顧客満足度向上
****** 販売促進活動の効果測定
**** サービス
***** 酒造事業
****** 技術サポート
****** アフターケアの強化
***** レストラン・土産物販売事業
****** クレーム対応
****** 保証サービス提供
****** 顧客対応
****** ロイヤルティプログラムの実施
*** 支援活動
**** インフラストラクチャ
***** 酒造事業
****** 設備投資
****** インフラ整備
***** レストラン・土産物販売事業
****** 工場の最新化
****** 安全対策
****** 店舗設計
****** ICTの導入
****[#orange] 人事・労務管理
***** 酒造事業
****** 人材育成
****** 労働環境の改善
***** レストラン・土産物販売事業
****** 労働力の確保
****** チームの統制
****** スタッフのトレーニング
****** 勤務シフトの管理
**** 技術開発
***** 酒造事業
****** 新技術の導入
****** R&Dの推進
***** レストラン・土産物販売事業
****** 製品革新
****** 製造技術の向上
****** サービス向上技術
****** 販売支援システム
**** 調達活動
***** 酒造事業
****** 安定したサプライチェーン
****** コスト削減
***** レストラン・土産物販売事業
****** 原材料の多様化
****** 供給リスクの分散
****** 調達プロセスの効率化
****** ベンダー管理

@endmindmap
----

=== 機能戦略

==== 販売

==== 生産

==== 購買

==== 総務

==== 財務

==== 資源

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
** 販売
** 生産
** 購買
** 総務
** 財務
** 資源
left side
** 価値連鎖
*** 主活動
**** 購買物流
***** 酒造事業
****** サプライチェーンの効率化
****** 品質管理
***** レストラン・土産物販売事業
****** 物流の最適化
****** 原材料の適時調達
****** 在庫管理
****** 新鮮な食材の安定供給
**** 製造
***** 酒造事業
****** 生産量の安定化
****** 専門技術の導入
***** レストラン・土産物販売事業
****** 生産プロセスの効率化
****** 衛生管理
****** 店舗での調理効率
****** 店内衛生
**** 出荷物流
***** 酒造事業
****** 出荷時の品質維持
****** ロジスティクスコスト削減
***** レストラン・土産物販売事業
****** 梱包効率の向上
****** 最適な出荷計画
****** 店舗への迅速な補充
****** 配送経路の最適化
**** マーケティング・販売
***** 酒造事業
****** 地元の認知度向上
****** ブランド構築
***** レストラン・土産物販売事業
****** 市場調査の精度向上
****** 商品差別化
****** 顧客満足度向上
****** 販売促進活動の効果測定
**** サービス
***** 酒造事業
****** 技術サポート
****** アフターケアの強化
***** レストラン・土産物販売事業
****** クレーム対応
****** 保証サービス提供
****** 顧客対応
****** ロイヤルティプログラムの実施
*** 支援活動
**** インフラストラクチャ
***** 酒造事業
****** 設備投資
****** インフラ整備
***** レストラン・土産物販売事業
****** 工場の最新化
****** 安全対策
****** 店舗設計
****** ICTの導入
****[#orange] 人事・労務管理
***** 酒造事業
****** 人材育成
****** 労働環境の改善
***** レストラン・土産物販売事業
****** 労働力の確保
****** チームの統制
****** スタッフのトレーニング
****** 勤務シフトの管理
**** 技術開発
***** 酒造事業
****** 新技術の導入
****** R&Dの推進
***** レストラン・土産物販売事業
****** 製品革新
****** 製造技術の向上
****** サービス向上技術
****** 販売支援システム
**** 調達活動
***** 酒造事業
****** 安定したサプライチェーン
****** コスト削減
***** レストラン・土産物販売事業
****** 原材料の多様化
****** 供給リスクの分散
****** 調達プロセスの効率化
****** ベンダー管理

@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* ドメイン
left side
** 企業ドメイン
*** 理念
**** 伝統と革新を融合させた酒造り
*** ビジョン
**** 文化と歴史を守り、次世代に伝える
*** ミッション
**** 高品質な日本酒と食文化の提供
** 事業ドメイン
*** 酒造事業
**** 誰に
***** 日本国内外の日本酒愛好者
**** 何を
***** 高品質な日本酒
****[#orange] どのように
***** 伝統技術を活かした製造
*** レストラン・土産物販売事業
**** 誰に
***** インバウンド観光客
***** 地元住民
**** 何を
***** 地元の高級食材を使った料理
***** 日本酒関連の土産物
****[#orange] どのように
***** 老舗の信頼性を活かした販売
***** 伝統技術と現代的サービスの融合
***** 地元の観光資源を活用した店舗展開
***** 観光資源を活用した店舗展開
***** 現代的サービスの提供
right side
** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== 業務領域(サブドメイン)

==== 中核の業務領域(コアサブドメイン)

==== 一般的な業務領域(汎用サブドメイン)

==== 補完的な業務領域(サポートサブドメイン)

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

