:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= ステンレス製品の受注・製作・据付を行うC社の事例

== 与件

【C社の概要】

　C社は、1955年創業で、資本金4,000万円、デザインを伴うビル建築用金属製品やモニュメント製品などのステンレス製品を受注・製作・据付する企業で、従業員は、営業部5名、製造部23名、総務部2名の合計30名で構成される。

　C社が受注しているビル建築用金属製品の主なものは、出入口の窓枠やサッシ、各種手摺、室内照明ボックスなどで、特別仕様の装飾性を要求されるステンレス製品である。またモニュメント製品は、作家（デザイナー）のデザインに従って製作するステンレス製の立体的造形物である。どちらも個別受注製品であり、C社の工場建屋の制約から設置高さ7m以内の製品である。主な顧客は、ビル建築用金属製品については建築用金属製品メーカー、モニュメント製品についてはデザイナーである。

　創業時は、サッシ、手摺など建築用金属製品の特注品製作から始め、特に鏡面仕上げなどステンレス製品の表面品質にこだわり、溶接技術や研磨技術を高めることに努力した。その後、ビル建築内装材の大型ステンレス加工、サイン（案内板）など装飾性の高い製品製作に拡大し、それに対応して設計技術者を確保し、設計から製作、据付工事までを受注する企業になった。

　その後、3代目である現社長は、就任前から溶接技術や研磨技術を生かした製品市場を探していたが、ある建築プロジェクトで外装デザインを行うデザイナーから、モニュメントの製作依頼を受けたことを契機として、特殊加工と仕上げ品質が要求されるステンレス製モニュメント製品の受注活動を始めた。

　モニュメント製品は受注量が減少したこともあったが、近年の都市型建築の増加に伴い製作依頼が増加している。受注量の変動が大きいものの、全売上高の40％を占め、ビル建築用金属製品と比較して付加価値が高いため、今後も受注の増加を狙っている。



【業務プロセス】

　ビル建築用金属製品、モニュメント製品の受注から引き渡しまでの業務フローは、以下のとおりである



　受注、設計、据付工事施工管理は営業部が担当する。顧客から引き合いがあると、受注製品ごとに受注から引き渡しに至る営業部担当者を決め、顧客から提供される設計図や仕様書などを基に、製作仕様と納期を確認して見積書を作成・提出し、契約締結後、製作図および施工図を作成して顧客承認を得る。通常、製作図および施工図の顧客承認段階では、仕様変更や図面変更などによって顧客とのやりとりが多く発生する。特にモニュメント製品では、造形物のイメージの摺合わせに時間を要する場合が多く、図面承認後の製作段階でも打ち合わせが必要な場合がある。設計には2次元CADを早くから使用している。

　その後、製作図を製造部に渡すことにより製作指示をする。製作終了後、据付工事があるものについては、営業部担当者が施工管理して据付工事を行い、検査後顧客に引き渡す。据付工事は社外の協力会社に依頼し、施工管理のみ社内営業部担当者が行っている。

　契約から製品引き渡しまでのリードタイムは、平均約2か月である。最終引き渡し日が設定されているが、契約、図面作成、顧客承認までの製作前プロセスに時間を要して製作期間を十分に確保できないことや、複雑な形状など高度な加工技術が必要な製品などの受注内容によって、製作期間が生産計画をオーバーするなど、納期の遅延が生じC社の大きな悩みとなっている。

　C社では、全社的な改善活動として「納期遅延の根絶」を掲げ、製作プロセスを含む業務プロセス全体の見直しを進めている。また、その対策の支援システムとしてIT化も検討している。



【生産の現状】

　製作工程は切断加工、曲げ加工、溶接・組立、研磨、最終検査の5工程である。切断加工工程と曲げ加工工程はNC加工機による加工であり、作業員2名が担当している。溶接・組立工程と研磨工程は溶接機や研磨機を用いた手作業であり、4班の作業チームが受注製品別に担当している。この作業チームは1班5名で編成され、熟練技術者が各班のリーダーとなって作業管理を行うが、各作業チームの技術力には差があり、高度な技術が必要な製作物の場合には任せられない作業チームもある。

　ビル建築用金属製品は切断加工、曲げ加工、溶接・組立までは比較的単純であるが、その後の研磨工程に技術を要する。また、モニュメント製品は立体的で複雑な曲線形状の製作が多く、全ての工程で製作図の理解力と高い加工技術が要求される。ビル建築用金属製品は製作完了後、製造部長と営業部の担当者が最終検査を行って、出荷する。モニュメント製品は、デザイナーの立ち会いの下、最終検査が行われ、この際デザイナーの指示によって製品に修整や手直しが生じる場合がある。

　生産計画は、製造部長が月次で作成している。月次生産計画は、営業部の受注情報、設計担当者の製品仕様情報によって、納期順にスケジューリングされるが、溶接・組立工程と研磨工程は加工の難易度などを考慮して各作業チームの振り分けを行いスケジューリングされる。C社の製品については基準となる工程順序や工数見積もりなどの標準化が確立しているとはいえない。

　工場は10年前に改築し、個別受注生産に適した設備や作業スペースのレイアウトに改善したが、最近の加工物の大型化によって狭隘な状態が進み、溶接・組立工程と研磨工程の作業スペースの確保が難しく、新たな製品の着手によって作業途中の加工物の移動などを強いられている。

　製造部長は、全社的改善活動のテーマである納期遅延の問題点を把握するため、作業時間中の作業者の稼働状態を調査した。それによると、不稼働の作業内容としては、「材料・工具運搬」と「歩行」のモノの移動に関連する作業が多く、その他作業者間の「打ち合わせ」、営業部担当者などとの打ち合わせのための「不在」が多く発生していた。


（令和2年度　中小企業診断士2次筆記試験　事例3　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startwbs

* C社
** 営業部
** 製造部
** 総務部

@endwbs
----

=== ビジネスモデル

[plantuml]
----
@startmindmap

* ビジネスモデル
-- 外部環境
--- 競争(XC)
--- 政治・社会・技術(XS)
--- マクロ経済(XE)
--- 市場(XM)
---- 就任前から溶接技術や研磨技術を生かした製品市場を探していたが、ある建築プロジェクトで外装デザインを行うデザイナーから、モニュメントの製作依頼を受けたことを契機として、特殊加工と仕上げ品質が要求されるステンレス製モニュメント製品の受注活動を始めた
----[#lightblue] 近年の都市型建築の増加に伴い製作依頼が増加している
** 内部環境
*** 顧客
**** 顧客セグメント(CS)
***** ビル建築用金属製品については建築用金属製品メーカー、モニュメント製品についてはデザイナー
**** 顧客関係(CR)
*** 価値
**** 価値提案(VP)
***** デザインを伴うビル建築用金属製品やモニュメント製品などのステンレス製品を受注・製作・据付する
***** C社が受注しているビル建築用金属製品の主なものは、出入口の窓枠やサッシ、各種手摺、室内照明ボックスなどで、特別仕様の装飾性を要求されるステンレス製品である
***** モニュメント製品は、作家（デザイナー）のデザインに従って製作するステンレス製の立体的造形物である
**** チャネル(CH)
*** インフラ
**** 主要活動(KA)
***** 個別受注製品であり、設計から製作、据付工事までを受注する
***** 特に鏡面仕上げなどステンレス製品の表面品質にこだわり、溶接技術や研磨技術を高めることに努力した
*****[#lightgreen] 設計から製作、据付工事までを受注する企業になった
***** 業務プロセス
****** 受注、設計、据付工事施工管理は営業部が担当する
******[#yellow] 通常、製作図および施工図の顧客承認段階では、仕様変更や図面変更などによって顧客とのやりとりが多く発生する
****** 特にモニュメント製品では、造形物のイメージの摺合わせに時間を要する場合が多く、図面承認後の製作段階でも打ち合わせが必要な場合がある
****** 設計には2次元CADを早くから使用している
****** 製作終了後、据付工事があるものについては、営業部担当者が施工管理して据付工事を行い、検査後顧客に引き渡す
****** 契約から製品引き渡しまでのリードタイムは、平均約2か月である
******[#yellow] 最終引き渡し日が設定されているが、契約、図面作成、顧客承認までの製作前プロセスに時間を要して製作期間を十分に確保できないことや、複雑な形状など高度な加工技術が必要な製品などの受注内容によって、製作期間が生産計画をオーバーするなど、納期の遅延が生じC社の大きな悩みとなっている
******[#orange] C社では、全社的な改善活動として「納期遅延の根絶」を掲げ、製作プロセスを含む業務プロセス全体の見直しを進めている
***** 生産の現状
****** 製作工程は切断加工、曲げ加工、溶接・組立、研磨、最終検査の5工程である
******[#yellow] 作業チームは1班5名で編成され、熟練技術者が各班のリーダーとなって作業管理を行うが、各作業チームの技術力には差があり、高度な技術が必要な製作物の場合には任せられない作業チームもある
****** ビル建築用金属製品は切断加工、曲げ加工、溶接・組立までは比較的単純であるが、その後の研磨工程に技術を要する
****** モニュメント製品は立体的で複雑な曲線形状の製作が多く、全ての工程で製作図の理解力と高い加工技術が要求される
****** モニュメント製品は、デザイナーの立ち会いの下、最終検査が行われ、この際デザイナーの指示によって製品に修整や手直しが生じる場合がある
****** 生産計画は、製造部長が月次で作成している
******[#yellow] C社の製品については基準となる工程順序や工数見積もりなどの標準化が確立しているとはいえない
******[#yellow] 不稼働の作業内容としては、「材料・工具運搬」と「歩行」のモノの移動に関連する作業が多く、その他作業者間の「打ち合わせ」、営業部担当者などとの打ち合わせのための「不在」が多く発生していた
**** 主要リソース(KR)
***** 従業員は、営業部5名、製造部23名、総務部2名の合計30名で構成される
**** 主要パートナー(KP)
*** 資金
**** 収益源(R$)
*****[#lightgreen] 受注量の変動が大きいものの、全売上高の40％を占め、ビル建築用金属製品と比較して付加価値が高いため、今後も受注の増加を狙っている
**** コスト構造(C$)

@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap

* SWOT
** 内部環境
***[#lightgreen] 強み
**** 建築用金属製品とモニュメント製品の受注・製作能力
**** 表面品質にこだわった高度なステンレス加工技術
**** 設計から製作、据付工事までを一貫して行える
***[#yellow] 弱み
**** 製作前プロセスに時間がかかり、納期遅延が生じる
**** 各チーム間の技術力の差
**** 標準化の欠如（工程順序や工数見積もり）
left side
** 外部環境
***[#lightblue] 機会
**** 都市型建築の増加に伴う製作依頼の増加
**** 高付加価値のある製品受注の増加を狙う
***[#red] 脅威
**** 生産計画をオーバーする製作期間のリスク
**** 高度な加工技術を必要とする複雑な製品への対応チャレンジ

@endmindmap
----

=== VRIO分析

[plantuml]
----
@startmindmap

* VRIO
** 経済的価値
*** ステンレス製品の特別仕様や装飾性による高付加価値の提供
*** 都市型建築の増加による需要の取り込み
** 希少性
*** 高度なステンレス加工技術と鏡面仕上げ技術
left side
** 模倣困難性
*** 設計から制作、据付工事までの一貫した受注能力
*** 経験豊富な熟練技術者の存在
** 組織能力

@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap

* ドメイン
** 企業ドメイン
*** 理念
**** 高品質で信頼性のある製品提供を通じた社会貢献
*** ビジョン
**** ステンレス加工技術を通じた新たな市場への進出と拡大
*** ミッション
**** 顧客の要望に応え、最高水準の品質を提供する
** 事業ドメイン
*** 誰に
**** 建築用金属製品を必要とする建築メーカーやデザイナー
*** 何を
**** 高度な技術を要するビル建築用金属製品やモニュメント製品
***[#orange] どのように
**** 設計から据付までの一貫したプロセスと高度な加工技術で提供

@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap

* 成長戦略
** 既存市場
***[#orange] 市場浸透
**** 既存の建築用金属製品市場におけるシェア拡大
*** 商品開発
**** モニュメント製品や特殊仕様製品の新規開発
** 新市場
*** 市場開発
**** 国内外の新しい建築プロジェクト向け市場開拓
*** 多角化
**** 水平的多角化
***** 加工技術を他製品ラインにも応用
**** 垂直型多角化
***** 原材料調達から製品据付までの垂直統合
**** 集中型多角化
***** 建築デザイン部門とのシナジー効果を創出
**** 集成型多角化
***** 建築関連分野全体でのポートフォリオの拡充

@endmindmapp
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** ドメイン
*** 企業ドメイン
**** 理念
***** 高品質で信頼性のある製品提供を通じた社会貢献
**** ビジョン
***** ステンレス加工技術を通じた新たな市場への進出と拡大
**** ミッション
***** 顧客の要望に応え、最高水準の品質を提供する
*** 事業ドメイン
**** 誰に
***** 建築用金属製品を必要とする建築メーカーやデザイナー
**** 何を
***** 高度な技術を要するビル建築用金属製品やモニュメント製品
****[#orange] どのように
***** 設計から据付までの一貫したプロセスと高度な加工技術で提供
right side
** 成長戦略
*** 既存市場
****[#orange] 市場浸透
***** 既存の建築用金属製品市場におけるシェア拡大
**** 商品開発
***** モニュメント製品や特殊仕様製品の新規開発
*** 新市場
**** 市場開発
***** 国内外の新しい建築プロジェクト向け市場開拓
**** 多角化
***** 水平的多角化
****** 加工技術を他製品ラインにも応用
***** 垂直型多角化
****** 原材料調達から製品据付までの垂直統合
***** 集中型多角化
****** 建築デザイン部門とのシナジー効果を創出
***** 集成型多角化
****** 建築関連分野全体でのポートフォリオの拡充

@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap

* 基本戦略
** コストリーダーシップ
*** 生産効率の向上によるコスト削減
** 差別化
*** 高度なステンレス加工技術による独自商品の提供
*** 高品質なビル建築用金属製品のデザイン性強化
**[#orange] 集中
*** 特殊仕様の建築プロジェクトに強みを持つ市場へ集中

@endmindmap
----

==== 競争戦略

[plantuml]
----
@startmindmap

* 競争戦略
** リーダー
*** 市場拡大
**** 新製品の導入によるシェアの拡大
*** 同質化
**** 競合他社との技術標準化への対応
** チャレンジャー
*** 差別化
**** 独自のデザインと技術を活かした製品開発
**[#orange] ニッチャー
*** 集中
**** 特定の市場ニーズに特化したサービス提供
** フォロワー
*** 追随
**** トレンドに合わせた製品の継続的アップデート

@endmindmap
----

==== 価値連鎖

[plantuml]
----
@startmindmap

* 価値連鎖
** 主活動
*** 購買物流
**** 迅速かつ効率的な材料調達とサプライチェーン管理
***[#orange] 製造
**** 高品質のステンレス製品の精密加工と生産効率
*** 出荷物流
**** 製品損傷を防ぐ効果的な出荷と配送システム
*** マーケティング・販売
**** 顧客特性に応じたターゲティングとプロモーション戦略
***[#orange] サービス
**** アフターサービスの強化と顧客満足度の向上
** 支援活動
*** インフラストラクチャ
**** 生産施設の整備と情報システムの強化
*** 人事・労務管理
**** 熟練技術者の育成と労働環境の改善
*** 技術開発
**** 新技術の導入と製品イノベーションの促進
*** 調達活動
**** コスト効率の高い購入契約と長期的な供給源の確保

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** 基本戦略
*** コストリーダーシップ
**** 生産効率の向上によるコスト削減
*** 差別化
**** 高度なステンレス加工技術による独自商品の提供
**** 高品質なビル建築用金属製品のデザイン性強化
***[#orange] 集中
**** 特殊仕様の建築プロジェクトに強みを持つ市場へ集中
** 競争戦略
*** リーダー
**** 市場拡大
***** 新製品の導入によるシェアの拡大
**** 同質化
***** 競合他社との技術標準化への対応
*** チャレンジャー
**** 差別化
***** 独自のデザインと技術を活かした製品開発
***[#orange] ニッチャー
**** 集中
***** 特定の市場ニーズに特化したサービス提供
*** フォロワー
**** 追随
***** トレンドに合わせた製品の継続的アップデート
right side
** 価値連鎖
*** 主活動
**** 購買物流
***** 迅速かつ効率的な材料調達とサプライチェーン管理
****[#orange] 製造
***** 高品質のステンレス製品の精密加工と生産効率
**** 出荷物流
***** 製品損傷を防ぐ効果的な出荷と配送システム
**** マーケティング・販売
***** 顧客特性に応じたターゲティングとプロモーション戦略
****[#orange] サービス
***** アフターサービスの強化と顧客満足度の向上
*** 支援活動
**** インフラストラクチャ
***** 生産施設の整備と情報システムの強化
**** 人事・労務管理
***** 熟練技術者の育成と労働環境の改善
**** 技術開発
***** 新技術の導入と製品イノベーションの促進
**** 調達活動
***** コスト効率の高い購入契約と長期的な供給源の確保

@endmindmap
----

=== 機能戦略

==== 販売

==== 生産

==== 購買

==== 総務

==== 財務

==== 資源

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
** 販売
** 生産
** 購買
** 総務
** 財務
** 資源
left side
** 価値連鎖
*** 主活動
**** 購買物流
***** 迅速かつ効率的な材料調達とサプライチェーン管理
****[#orange] 製造
***** 高品質のステンレス製品の精密加工と生産効率
**** 出荷物流
***** 製品損傷を防ぐ効果的な出荷と配送システム
**** マーケティング・販売
***** 顧客特性に応じたターゲティングとプロモーション戦略
****[#orange] サービス
***** アフターサービスの強化と顧客満足度の向上
*** 支援活動
**** インフラストラクチャ
***** 生産施設の整備と情報システムの強化
**** 人事・労務管理
***** 熟練技術者の育成と労働環境の改善
**** 技術開発
***** 新技術の導入と製品イノベーションの促進
**** 調達活動
***** コスト効率の高い購入契約と長期的な供給源の確保

@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* ドメイン

left side
** 企業ドメイン
*** 理念
**** 高品質で信頼性のある製品提供を通じた社会貢献
*** ビジョン
**** ステンレス加工技術を通じた新たな市場への進出と拡大
*** ミッション
**** 顧客の要望に応え、最高水準の品質を提供する
** 事業ドメイン
*** 誰に
**** 建築用金属製品を必要とする建築メーカーやデザイナー
*** 何を
**** 高度な技術を要するビル建築用金属製品やモニュメント製品
***[#orange] どのように
**** 設計から据付までの一貫したプロセスと高度な加工技術で提供

right side

** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== 業務領域(サブドメイン)

==== 中核の業務領域(コアサブドメイン)

==== 一般的な業務領域(汎用サブドメイン)

==== 補完的な業務領域(サポートサブドメイン)

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

