:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 農業生産法人B社の事例

== 与件

　B社は、資本金450万円、社長をはじめ従業者10名（パート・アルバイト含む）の農業生産法人（現・農地所有適格法人）である。ハーブの無農薬栽培、ハーブ乾燥粉末の一次加工・出荷を行っている。

　B社は、本州から海を隔てたX島にある。島は車で2時間もあれば一周できる広さで、島内各所には海と空、緑が鮮やかな絶景スポットがある。比較的温暖な気候で、マリンスポーツや釣りが1年の長い期間楽しめ、夜は満天の星空が広がる。島の主力産業は、農業と観光業である。ただし島では、若年層の人口流出や雇用機会不足、人口の高齢化による耕作放棄地の問題、農家所得の減少などが深刻化し、地域の活力が低下して久しい。

　B社の設立は10年ほど前にさかのぼる。この島で生まれ育ち、代々農業を営む一家に生まれたB社社長が、こうした島の窮状を打開したいと考えたことがきっかけである。B社設立までの経緯は以下のとおりである。

　社長は、セリ科のハーブY（以下「ハーブ」と称する）に目を付けた。このハーブはもともと島に自生していた植物で、全国的な知名度はないが、島内では古くから健康・長寿の効能があると言い伝えられてきた。現在でも祝いの膳や島のイベント時に必ず食べる風習が残り、とくに高齢者は普段からおひたしや酢みそあえにして食べる。社長はこのハーブの本格的な栽培に取り組み、島の新たな産業として発展させようと考えた。

　まず社長が取り組んだのは、ハーブの栽培手法の確立であった。このハーブは自生植物であるため、栽培ノウハウは存在しなかった。しかし、社長は農業試験場の支援を得て実験を繰り返し、無農薬で高品質のハーブが同じ耕作地で年に4～5回収穫できる効率的な栽培方法を開発した。一面に広がるハーブ畑は、生命力あふれる緑の葉が海から吹く風に揺れ、青い空と美しいコントラストを生み出している。

　一般的にハーブの用途は広く、お茶や調味料、健康食品などのほか、アロマオイルや香水などの原材料にもなる。社長は次に、このハーブを乾麺や焼き菓子に練りこんだ試作品をOEM企業に生産委託し、大都市で開催される離島フェアなどに出展して販売を行った。しかし、その売上げは芳しくなかった。社長は、このハーブと島の知名度が大消費地では著しく低いことを痛感し、ハーブを使った自社による製品開発をいったん諦めた。社長はハーブの販売先を求めて、試行錯誤を続けた。

　B社設立の直接的な契機となったのは、社長が大手製薬メーカーZ社と出合ったことである。消費者の健康志向を背景にますます拡大基調にあるヘルスケア市場では、メーカー間の競争も激しい。Z社は当時、希少性と効能を兼ね備えた差別的要素の強いヘルスケア製品の開発可能性を探っており、美しい島で栽培された伝統あるハーブが有するアンチエイジングの効能と社長の高品質かつ安全性を追求する姿勢、島への思い入れを高く評価した。社長もZ社もすぐに取引を開始したかったが、軽い割にかさばるハーブを島から島外の工場へ輸送するとなるとコストがかかることがネックとなった。

　そこで社長自ら島内に工場を建設し、栽培したハーブを新鮮なうちに乾燥粉末にするところまで行い、輸送コスト削減を図ろうと考えた。Z社もそれに同意した。その結果、B社はハーブの栽培・粉末加工・出荷を行うための事業会社として、10年ほど前に設立された。

　Z社は予定どおり、B社製造のハーブの乾燥粉末を原材料として仕入れ、これをさらに本州の工場で加工し、ドリンクやサプリメントとして全国販売した。これらの製品は、島の大自然とハーブからもたらされる美を意識させるパッケージで店頭に並び、主として30～40歳代の女性層の支持を獲得した。この島の空港や港の待合室にも広告看板が設置され、島とハーブの名前が大きく明示されている。そのため、とくにヘルスケアに関心の高い人たちから、このハーブが島の顔として認知されるようになってきた。こうした経緯もあって、島民は昨今B社の存在を誇りに感じ始めている。

　ただし、Z社のこの製品も発売から約10年の歳月を経て、売れ行きが鈍ってきた。このところ、B社とZ社とのハーブの取引量は徐々に減少している。Z社担当者からは先日、ブランド刷新のため、あと2～3年でこの製品を製造中止する可能性が高いことを告げられた。

　現在のB社は、このハーブ以外に、6～7種類の別のハーブの栽培・乾燥粉末加工を行うようになっている。最近ではこのうち、安眠効果があるとされるハーブ（Yとは異なるハーブ）が注目を集めている。Z社との取引実績が安心材料となり、複数のヘルスケアメーカーなどから安眠系サプリメントなどの原材料として使いたいと引き合いが来るようになった。しかし、取引が成立しても、Z社との取引に比べるとまだ少量であり、B社の事業がZ社との取引に依存している現状は変わらない。最近になって、社長は自社ブランド製品の販売に再びチャレンジしたいという思いや、島の活性化への思いがさらに強くなってきた。試しに、安眠効果のあるハーブを原材料とした「眠る前に飲むハーブティー」というコンセプトの製品をOEM企業に生産委託し、自社オンラインサイトで販売してみたところ、20歳代後半～50歳代の大都市圏在住の女性層から注文が来るようになった。

　島の数少ない事業家としての責任もあるため、社長は早期に事業の見直しを行うべきだと考え、中小企業診断士に相談することにした。


（令和2年度　中小企業診断士2次筆記試験　事例2　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startwbs

* B社
** 栽培
** 加工
** 販売

@endwbs
----

=== ビジネスモデル

[plantuml]
----
@startmindmap

* ビジネスモデル
-- 外部環境
--- 競争(XC)
--- 政治・社会・技術(XS)
----[#lightblue] 比較的温暖な気候で、マリンスポーツや釣りが1年の長い期間楽しめ、夜は満天の星空が広がる
----[#red] 若年層の人口流出や雇用機会不足、人口の高齢化による耕作放棄地の問題、農家所得の減少
--- マクロ経済(XE)
--- 市場(XM)
---- 一般的にハーブの用途は広く、お茶や調味料、健康食品などのほか、アロマオイルや香水などの原材料にもなる
----[#lightblue] 消費者の健康志向を背景にますます拡大基調にあるヘルスケア市場
----[#red] ブランド刷新のため、あと2～3年でこの製品を製造中止する可能性が高い
----[#lightblue] Z社との取引実績が安心材料となり、複数のヘルスケアメーカーなどから安眠系サプリメントなどの原材料として使いたいと引き合いが来るようになった
** 内部環境
*** 顧客
**** 顧客セグメント(CS)
***** 主として30～40歳代の女性層
***** ヘルスケアに関心の高い人たち
***** 20歳代後半～50歳代の大都市圏在住の女性層
**** 顧客関係(CR)
*****[#lightgreen] 島の大自然とハーブからもたらされる美を意識させるパッケージで店頭に並び、主として30～40歳代の女性層の支持を獲得
*** 価値
**** 価値提案(VP)
***** ハーブの無農薬栽培、ハーブ乾燥粉末の一次加工・出荷
***** このハーブはもともと島に自生していた植物で、全国的な知名度はないが、島内では古くから健康・長寿の効能があると言い伝えられてきた
*****[#lightgreen] 美しい島で栽培された伝統あるハーブが有するアンチエイジングの効能と社長の高品質かつ安全性を追求する姿勢、島への思い入れを高く評価
***** 6～7種類の別のハーブの栽培・乾燥粉末加工
*****[#lightgreen] 安眠効果があるとされるハーブ（Yとは異なるハーブ）が注目を集めている
***** 安眠効果のあるハーブを原材料とした「眠る前に飲むハーブティー」というコンセプトの製品
**** チャネル(CH)
*****[#yellow] このハーブと島の知名度が大消費地では著しく低いことを痛感し、ハーブを使った自社による製品開発をいったん諦めた
***** B社製のハーブの乾燥粉末を原材料として仕入れ、これをさらに本州の工場で加工し、ドリンクやサプリメントとして全国販売
*****[#orange] 自社ブランド製品の販売に再びチャレンジ
***** 自社オンラインサイト
*** インフラ
**** 主要活動(KA)
*****[#lightgreen] 社長は農業試験場の支援を得て実験を繰り返し、無農薬で高品質のハーブが同じ耕作地で年に4～5回収穫できる効率的な栽培方法を開発
***** 島内に工場を建設し、栽培したハーブを新鮮なうちに乾燥粉末にするところまで行い、輸送コスト削減を図ろうと考えた
**** 主要リソース(KR)
***** 資本金450万円、社長をはじめ従業者10名（パート・アルバイト含む）
**** 主要パートナー(KP)
*****[#lightgreen] 大手製薬メーカーZ社
*** 資金
**** 収益源(R$)
*****[#yellow] 取引が成立しても、Z社との取引に比べるとまだ少量であり、B社の事業がZ社との取引に依存している現状は変わらない
**** コスト構造(C$)

@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap

* SWOT
** 内部環境
***[#lightgreen] 強み
**** 無農薬の高品質ハーブ栽培方法の開発
**** 健康と美を意識した製品パッケージと顧客支持
**** 大手製薬メーカーとの提携
***[#yellow] 弱み
**** ブランドとハーブの知名度の低さ
**** Z社に依存した収益構造
left side
** 外部環境
***[#lightblue] 機会
**** 健康志向の消費者市場の拡大
**** 安眠系サプリメント市場への参入機会
**** ヘルスケアメーカーからの需要増加
***[#red] 脅威
**** 若年層の人口流出と雇用機会不足
**** 競争の激化と製品製造中止の可能性

@endmindmap
----

=== VRIO分析

[plantuml]
----
@startmindmap

* VRIO
** 経済的価値
*** 高品質の無農薬ハーブによる顧客の健康志向需要の獲得
*** 長年伝えられる健康・長寿の効能
** 希少性
*** 島特有の環境で育まれる伝統的なハーブ
*** 健康・美を意識する特定の顧客セグメントへの深いアピール
left side
** 模倣困難性
*** 無農薬で効率的なハーブ栽培方法の開発
*** 大手製薬メーカーZ社との信頼関係
** 組織能力
*** 少人数の組織での柔軟な生産体制と顧客関係の構築
*** 島内での生産・加工により輸送コストを削減するインフラ整備

@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap

* ドメイン
** 企業ドメイン
*** 理念
**** 持続可能な方法で地域資源を活用し、健康と美を追求する
*** ビジョン
**** 島のハーブを通じて全国規模での知名度と信頼を獲得する
*** ミッション
**** 高品質かつ安全な製品を提供することで、消費者の健康と幸福に貢献する
** 事業ドメイン
*** 誰に
**** 健康志向の高い30～50歳代の女性
*** 何を
**** 無農薬栽培ハーブを用いた健康・美容関連製品
***[#orange] どのように
**** オンライン販売とパートナーシップを通じた全国展開

@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap

* 成長戦略
** 既存市場
*** 市場浸透
**** 大都市圏の既存顧客へのさらなる浸透
***[#orange] 商品開発
**** 新たなハーブティーやサプリメントの製品ラインナップ拡充
** 新市場
***[#orange] 市場開発
**** 全国的な健康志向市場へのアプローチ
*** 多角化
**** 水平的多角化
***** 健康・美容関連商品の新カテゴリへの展開
**** 垂直型多角化
***** ハーブの栽培から製品開発、販売までの一体化
**** 集中型多角化
***** ハーブを基軸とした関連業界内の新たなビジネスチャンスの模索
**** 集成型多角化
***** 他の食品・飲料メーカーとのパートナーシップによる新たな商品開発

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** ドメイン
*** 企業ドメイン
**** 理念
***** 持続可能な方法で地域資源を活用し、健康と美を追求する
**** ビジョン
***** 島のハーブを通じて全国規模での知名度と信頼を獲得する
**** ミッション
***** 高品質かつ安全な製品を提供することで、消費者の健康と幸福に貢献する
*** 事業ドメイン
**** 誰に
***** 健康志向の高い30～50歳代の女性
**** 何を
***** 無農薬栽培ハーブを用いた健康・美容関連製品
****[#orange] どのように
***** オンライン販売とパートナーシップを通じた全国展開
right side
** 成長戦略
*** 既存市場
**** 市場浸透
***** 大都市圏の既存顧客へのさらなる浸透
****[#orange] 商品開発
***** 新たなハーブティーやサプリメントの製品ラインナップ拡充
*** 新市場
****[#orange] 市場開発
***** 全国的な健康志向市場へのアプローチ
**** 多角化
***** 水平的多角化
****** 健康・美容関連商品の新カテゴリへの展開
***** 垂直型多角化
****** ハーブの栽培から製品開発、販売までの一体化
***** 集中型多角化
****** ハーブを基軸とした関連業界内の新たなビジネスチャンスの模索
***** 集成型多角化
****** 他の食品・飲料メーカーとのパートナーシップによる新たな商品開発

@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap

* 基本戦略
** コストリーダーシップ
*** 無農薬による生産効率の向上でコスト削減を図る
**[#orange] 差別化
*** 高品質無農薬ハーブによる製品の独自性強化
*** 健康志向の明確なブランドイメージとストーリーで市場に差別化を図る
**[#orange] 集中
*** 健康志向の30～50歳代の女性のニッチ市場に集中したマーケティング戦略

@endmindmap
----

==== 競争戦略

[plantuml]
----
@startmindmap

* 競争戦略
** リーダー
*** 市場拡大
**** 全国展開に向けたプロモーション活動強化
*** 同質化
**** 同業他社の動向を注視しつつ、自社製品の特性を維持
** チャレンジャー
*** 差別化
**** 無農薬という特性を強調し、ブランド力を高める
**[#orange] ニッチャー
*** 集中
**** 特定の健康志向顧客層に深く根ざす戦略
** フォロワー
*** 追随
**** 同業他社の成功事例を分析し、最適な施策を導入

@endmindmapp
----

==== 価値連鎖

[plantuml]
----
@startmindmap

* 価値連鎖
** 主活動
*** 購買物流
**** 地元産の無農薬ハーブの効率的な調達システム
*** 製造
**** 高品質を維持するための精製プロセスと製造設備の最適化
*** 出荷物流
**** 全国へのスムーズな配送を実現する物流ネットワーク
***[#orange] マーケティング・販売
**** オンラインとリアルイベントを活用した効果的なプロモーション
***[#orange] サービス
**** 顧客フィードバックを活用したアフターサービスの強化
** 支援活動
*** インフラストラクチャ
**** 先進的な設備と管理システムによる事業運営の効率化
*** 人事・労務管理
**** 専門知識を持つスタッフの教育と維持
*** 技術開発
**** 品質向上と新製品開発を支える研究開発活動
*** 調達活動
**** サステイナブルな資源調達に向けたパートナーシップ構築

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** 基本戦略
*** コストリーダーシップ
**** 無農薬による生産効率の向上でコスト削減を図る
***[#orange] 差別化
**** 高品質無農薬ハーブによる製品の独自性強化
**** 健康志向の明確なブランドイメージとストーリーで市場に差別化を図る
***[#orange] 集中
**** 健康志向の30～50歳代の女性のニッチ市場に集中したマーケティング戦略
** 競争戦略
*** リーダー
**** 市場拡大
***** 全国展開に向けたプロモーション活動強化
**** 同質化
***** 同業他社の動向を注視しつつ、自社製品の特性を維持
*** チャレンジャー
**** 差別化
***** 無農薬という特性を強調し、ブランド力を高める
***[#orange] ニッチャー
**** 集中
***** 特定の健康志向顧客層に深く根ざす戦略
*** フォロワー
**** 追随
***** 同業他社の成功事例を分析し、最適な施策を導入
right side
** 価値連鎖
*** 主活動
**** 購買物流
***** 地元産の無農薬ハーブの効率的な調達システム
**** 製造
***** 高品質を維持するための精製プロセスと製造設備の最適化
**** 出荷物流
***** 全国へのスムーズな配送を実現する物流ネットワーク
****[#orange] マーケティング・販売
***** オンラインとリアルイベントを活用した効果的なプロモーション
****[#orange] サービス
***** 顧客フィードバックを活用したアフターサービスの強化
*** 支援活動
**** インフラストラクチャ
***** 先進的な設備と管理システムによる事業運営の効率化
**** 人事・労務管理
***** 専門知識を持つスタッフの教育と維持
**** 技術開発
***** 品質向上と新製品開発を支える研究開発活動
**** 調達活動
***** サステイナブルな資源調達に向けたパートナーシップ構築

@endmindmap
----

=== 機能戦略

==== 販売

==== 生産

==== 購買

==== 総務

==== 財務

==== 資源

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
** 販売
** 生産
** 購買
** 総務
** 財務
** 資源
left side
** 価値連鎖
*** 主活動
**** 購買物流
***** 地元産の無農薬ハーブの効率的な調達システム
**** 製造
***** 高品質を維持するための精製プロセスと製造設備の最適化
**** 出荷物流
***** 全国へのスムーズな配送を実現する物流ネットワーク
****[#orange] マーケティング・販売
***** オンラインとリアルイベントを活用した効果的なプロモーション
****[#orange] サービス
***** 顧客フィードバックを活用したアフターサービスの強化
*** 支援活動
**** インフラストラクチャ
***** 先進的な設備と管理システムによる事業運営の効率化
**** 人事・労務管理
***** 専門知識を持つスタッフの教育と維持
**** 技術開発
***** 品質向上と新製品開発を支える研究開発活動
**** 調達活動
***** サステイナブルな資源調達に向けたパートナーシップ構築

@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* ドメイン

left side
** 企業ドメイン
*** 理念
**** 持続可能な方法で地域資源を活用し、健康と美を追求する
*** ビジョン
**** 島のハーブを通じて全国規模での知名度と信頼を獲得する
*** ミッション
**** 高品質かつ安全な製品を提供することで、消費者の健康と幸福に貢献する
** 事業ドメイン
*** 誰に
**** 健康志向の高い30～50歳代の女性
*** 何を
**** 無農薬栽培ハーブを用いた健康・美容関連製品
***[#orange] どのように
**** オンライン販売とパートナーシップを通じた全国展開

right side

** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== 業務領域(サブドメイン)

==== 中核の業務領域(コアサブドメイン)

==== 一般的な業務領域(汎用サブドメイン)

==== 補完的な業務領域(サポートサブドメイン)

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

