:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 豆腐の製造販売業者B社の事例

== 与件

　B社は資本金300 万円、社長を含む従業者数15 名の豆腐の製造販売業者である。B 社は清流が流れる地方都市X 市に所在する。この清流を水源とする地下水は良質な軟水で、滑らかな豆腐づくりに向く。

　1953 年（昭和28年）、現社長の祖父がX 市の商店街にB 社を創業した。地元産大豆、水にこだわった豆腐は評判となり、品評会でも度々表彰された。なお、X 市は室町時代に戦火を避けて京都から移り住んだ人々の影響で、小京都の面影を残している。そのため、京文化への親近感が強く、同地の職人には京都の老舗で修行した者が多い。同地の繁盛店は、B 社歴代社長、新しい素材を使った菓子で人気を博す和菓子店の店主、予約が取りにくいと評判の割烹の板前など京都で修行した職人が支えている。

　1981 年（昭和56 年）、創業者の病をきっかけに、経営は息子の2 代目に引き継がれた。その頃、X 市でもスーパーマーケットなど量販店の出店が増加し、卸販売も行うようになった。従来の商店街の工場兼店舗が手狭になったため、良質な地下水を採取できる農村部の土地に工場を新設した。パートの雇用も増やし、生産量を拡大した。

　2000 年（平成12 年）、創業者の孫にあたる現社長が、京都での修行を終えてB 社を継承した。その頃、地場資本のスーパーマーケットからプライベート・ブランド（PB）の製造呼びかけがあった。国産大豆を使いながらも、価格を抑え、集客の目玉とするPB であった。地元産大豆にこだわった祖父と父のポリシーに反するが、事業拡大の好機と捉え、コンペ（企画競争型の業者選定会）に参加し、受注に成功した。そしてPB 製造のための材料用倉庫と建屋も新築し、パートも増やした。その後、数度のコンペで受注契約を繰り返し、最盛期はB 社売上比率の約半分がPB で占められた。しかし、2015 年（平成27 年）のコンペで大手メーカーに敗れ、契約終了となった。

　PB の失注のタイミングで、X 市の大手米穀店Y 社からアプローチがあり、協議の結果、農村部の工場の余剰設備をY 社へ売却し、整理人員もY 社が雇用した。X 市は豊富な水を活かした米の生産も盛んで、Y 社は同地の米の全国向けEC サイトに注力している。Y 社社長は以前より在庫用倉庫と炊飯に向く良質な軟水を大量に採取できる井戸を探していた。Y 社は建屋を改修し、B 社の地下水を購入する形で、Y 社サイトのお得意さまに限定販売するペットボトル入り水の製造を開始した。またY 社は「X 市の魅力を全国に」との思いからX 市企業の佃煮、干物などもY 社サイトでコラボ企画と称して販売している。近年、グルメ雑誌でY 社サイトの新米、佃煮が紹介されたのをきっかけに、全国の食通を顧客として獲得し、サイトでの売上が拡大している。

　B社社長はPB 関連施設の整理のめどが立った頃、B 社の将来について、残った従業員と会議を重ねた。その結果、各地で成功例のある冷蔵販売車を使った豆腐の移動販売の開始を決意した。売上の早期回復のために移動販売はフランチャイズ方式を採用した。先行事例を参考に、フランチャイジーは加盟時に登録料と冷蔵販売車を用意し、以降はB 社から商品を仕入れるのみで、その他のフィーは不要とする方式とした。また、フランチャイジーは担当地域での販売に専念し、B 社はその他のマーケティング活動、支援活動を担当する。結果、元商店経営者やB社の元社員などがフランチャイジーとして加盟した。

　移動販売の開始と同時に原材料を全て地元産大豆に戻し、品揃えも大幅に見直した。手頃な価格の絹ごし豆腐、木綿豆腐の他、柚子 豆腐、銀杏豆腐などの季節の変わり豆腐も月替わりの商品として加えた。新商品のグラム当たり単価はいずれもスーパーマーケットの高価格帯商品よりも高く設定した。

移動販売は戸別訪問の他に、豆腐の製造販売店がない商店街、遊戯施設、病院などの駐車場でも許可を得て販売している。駐車場での販売は高齢者が知り合いを電話で呼び、井戸端会議のきっかけとなることも多い。移動販売の開始後、顧客数は拡大したものの客単価は伸び悩んでいたが、フランチャイジーの1 人がデモンストレーション販売をヒントに始めた販売方法が客単価を引き上げた。自身が抱える在庫をどうせ廃棄するならば、と小分けにし、使い捨て容器に盛り付け、豆腐に合った調味料をかけて試食を勧めながら、商品説明を積極的に行った結果、次第に高単価商品が売れ始めた。

　フランチャイジーと高齢者顧客とのやり取りは来店前の電話での通話が主体である。インスタント・メッセンジャー（IM）の利用を勧めた時もあったが敬遠されたため、電話がメインになっている。ただし若年層にはIM によるテキストでのやり取りの方が好まれ、自社の受注用サイトを作る計画もあったが、ノウハウもなく、投資に見合った利益が見込めないとの判断により、IM で十分という結論に達した。

　移動販売の開始以降、毎年秋には農村部の工場に顧客リストの中から買い上げ額上位のお得意さまの家族を招いて、日頃のご愛顧への感謝を伝える収穫祭と称するイベントを実施してきた。これは昔ながらの方法で大豆の収穫を体験するイベントである。収穫の喜びを顧客と共有すると共に、B 社の顧客は高齢者が多いため、一緒に昔を懐かしむ目的で始めた。しかし、食べ物が多くの人の努力を経て食卓に届くことを孫に教えたいという声が増え、年を追うごとに子連れの参加者が多くなった。収穫体験の後には食事会を開き、B 社商品を使った肉豆腐や湯豆腐を振る舞う。ここで参加者が毎年楽しみにしているのは炊きたての新米に、出来たての温かい豆腐を乗せ、鰹節としょうゆ、薬味の葱ねぎ少々をかけた豆腐丼であった。豆腐丼は祖父の時代からB 社でまかないとして食べてきたものである。「豆腐に旅をさせるな」といわれるように出来たての豆腐の風味が最も良く、豆腐と同じ水で炊き上げた新米との相性も合って毎年好評を得ていた。同市の年齢分布を踏まえると主婦層の顧客が少ないという課題を抱えつつ、移動販売は高齢層への販売を伸ばし続けていた。

　しかしながら、新型コロナウイルス感染症のまん延に伴い、以降、試食を自粛した。また、人的接触を避けるために、駐車場での販売から戸別販売への変更を希望したり、戸別訪問を断ったりする顧客が増えてきた。収穫祭では収穫体験のみを実施し、室内での食事会を中止した。その際に、豆腐丼を惜しむ声が複数顧客より寄せられた。B 社社長が全国に多数展開される豆腐EC サイトを調べたところ、多くのサイトで豆乳とにがりをセットにした商品が販売されていることを知り「手作り豆腐セット」を開発し、移動販売を開始した。顧客が豆乳とにがりを混ぜ、蒸し器で仕上げる手間のかかる商品であるが、出来たての豆腐を味わえる。リモートワークの浸透を受け、自宅での食事にこだわりを持つ家庭が増え、お得意さま以外の主婦層にも人気を博している。この商品のヒットもあり、何とかもちこたえてきたものの、移動販売の売上は3 割落ち込んだままである。

　そこで、人的接触を控えたい、自宅を不在にする日にも届けてほしいという高齢層や主婦層の声を踏まえ、生協を参考に冷蔵ボックスを使った置き配の開始も検討している。そして、危機こそ好機と捉え、豆腐やおからを材料とする菓子類による主婦層の獲得や、地元産大豆の魅力を伝える全国向けネット販売といった夢をこの機にかなえたいと考えている。しかし、具体的な打ち手に悩んだB 社社長は2021 年（令和3 年）8 月末に中小企業診断士に相談することとした。

（令和3年度　中小企業診断士2次筆記試験　事例2　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startwbs

* B社
** 製造
** 販売課

@endwbs
----

=== ビジネスモデル

[plantuml]
----
@startmindmap

* ビジネスモデル
-- 外部環境
--- 競争(XC)
---- スーパーマーケットなど量販店の出店が増加
---- 大手メーカーに敗れ、PB 契約終了
---- 豆腐EC サイトの多数展開
--- 政治・社会・技術(XS)
---- B社は清流が流れる地方都市X 市に所在する。この清流を水源とする地下水は良質な軟水で、滑らかな豆腐づくりに向く。
---- 同地の職人には京都の老舗で修行した者が多い。
---- X市は豊富な水を活かした米の生産も盛んで、Y 社は同地の米の全国向けEC サイトに注力している。
---- 新型コロナウイルス感染症のまん延に伴い、試食を自粛した。
--- マクロ経済(XE)
--- 市場(XM)
** 内部環境
*** 顧客
**** 顧客セグメント(CS)
***** 全国の食通
***** 高齢者
***** 若年層
***** 主婦層
***** 自宅での食事にこだわりを持つ家庭
***** 豆腐やおからを材料とする菓子類による主婦層の獲得
**** 顧客関係(CR)
***** 駐車場での販売は高齢者が知り合いを電話で呼び、井戸端会議のきっかけとなることも多い。
***** 自身が抱える在庫をどうせ廃棄するならば、と小分けにし、使い捨て容器に盛り付け、豆腐に合った調味料をかけて試食を勧めながら、商品説明を積極的に行った結果、次第に高単価商品が売れ始めた。
***** フランチャイジーと高齢者顧客とのやり取りは来店前の電話での通話が主体である。インスタント・メッセンジャー（IM）の利用を勧めた時もあったが敬遠されたため、電話がメインになっている。
***** 若年層にはIM によるテキストでのやり取りの方が好まれ、自社の受注用サイトを作る計画もあったが、ノウハウもなく、投資に見合った利益が見込めないとの判断により、IM で十分という結論に達した。
***** 毎年秋には農村部の工場に顧客リストの中から買い上げ額上位のお得意さまの家族を招いて、日頃のご愛顧への感謝を伝える収穫祭と称するイベントを実施してきた。
****** 「豆腐に旅をさせるな」といわれるように出来たての豆腐の風味が最も良く、豆腐と同じ水で炊き上げた新米との相性も合って毎年好評を得ていた。
***** 同市の年齢分布を踏まえると主婦層の顧客が少ないという課題を抱えつつ、移動販売は高齢層への販売を伸ばし続けていた。
*** 価値
**** 価値提案(VP)
***** 地元産大豆、水にこだわった豆腐は評判となり、品評会でも度々表彰された。
***** プライベート・ブランド（PB）の製造
****** 地元産大豆にこだわった祖父と父のポリシーに反するが、事業拡大の好機と捉え、コンペ（企画競争型の業者選定会）に参加し、受注に成功した。
***** 豆腐の移動販売
****** 手ごろな価格の絹ごし豆腐、木綿豆腐の他、柚子 豆腐、銀杏豆腐などの季節の変わり豆腐も月替わりの商品として加えた。
****** 新商品のグラム当たり単価はいずれもスーパーマーケットの高価格帯商品よりも高く設定した。
***** 「手作り豆腐セット」
**** チャネル(CH)
***** 卸売販売も行う
***** Y社サイトのお得意さまに限定販売するペットボトル入り水の製造
***** グルメ雑誌
***** フランチャイズ方式
***** 移動販売は個別訪問の他に、豆腐の製造販売店がない商店街、遊戯施設、病院などの駐車場でも許可を得て販売している。
***** 人的接触を避けるために、駐車場での販売から戸別販売への変更を希望したり、戸別訪問を断ったりする顧客が増えてきた。
***** 人的接触を控えたい、自宅を不在にする日にも届けてほしいという高齢層や主婦層の声を踏まえ、生協を参考に冷蔵ボックスを使った置き配の開始も検討している。
***** 地元産大豆の魅力を伝える全国向けネット販売
*** インフラ
**** 主要活動(KA)
***** フランチャイジーは担当地域での販売に専念し、B 社はその他のマーケティング活動、支援活動を担当する。
**** 主要リソース(KR)
***** 資本金300 万円、社長を含む従業者数15 名
***** 良質な地下水を採取できる農村部の土地に工場を新設
***** PB 製造のための材料用倉庫と建屋も新築
***** 農村部の工場の余剰設備をY 社へ売却し、整理人員もY 社が雇用
***** フランチャイジーは加盟時に登録料と冷蔵販売車を用意し、以降はB 社から商品を仕入れるのみで、その他のフィーは不要とする方式とした。
**** 主要パートナー(KP)
***** 新しい素材を使った菓子で人気を博す和菓子店の店主、予約が取りにくいと評判の割烹の板前など京都で修行した職人が支えている。
***** 大手米穀店Y 社
*** 資金
**** 収益源(R$)
***** 最盛期はB 社売上比率の約半分がPB で占められた。
***** 移動販売の開始後、顧客数は拡大したものの客単価は伸び悩んでいたが、フランチャイジーの1 人がデモンストレーション販売をヒントに始めた販売方法が客単価を引き上げた。
***** 移動販売の売上は3 割落ち込んだままである。
**** コスト構造(C$)

@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap

* SWOT
** 内部環境
***[#lightgreen] 強み
***[#yellow] 弱み
left side
** 外部環境
***[#lightblue] 機会
***[#red] 脅威

@endmindmap
----

=== VRIO分析

[plantuml]
----
@startmindmap

* VRIO
** 経済的価値
** 希少性
left side
** 模倣困難性
** 組織能力

@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap

* ドメイン
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように

@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap

* 成長戦略
** 既存市場
*** 市場浸透
*** 商品開発
** 新市場
*** 市場開発
*** 多角化
**** 水平的多角化
**** 垂直型多角化
**** 集中型多角化
**** 集成型多角化

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** ドメイン
right side
** 成長戦略

@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap

* 基本戦略
** コストリーダーシップ
** 差別化
** 集中

@endmindmap
----

==== 競争戦略

[plantuml]
----
@startmindmap

* 競争戦略
** リーダー
*** 市場拡大
*** 同質化
** チャレンジャー
*** 差別化
** ニッチャー
*** 集中
** フォロワー
*** 追随

@endmindmap
----

==== 価値連鎖

[plantuml]
----
@startmindmap

* 価値連鎖
** 主活動
*** 購買物流
*** 製造
*** 出荷物流
*** マーケティング・販売
*** サービス
** 支援活動
*** インフラストラクチャ
*** 人事・労務管理
*** 技術開発
*** 調達活動

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** 基本戦略
** 競争戦略
right side
** 価値連鎖

@endmindmap
----

=== 機能戦略

==== 販売

==== 生産

==== 購買

==== 総務

==== 財務

==== 資源

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
** 販売
** 生産
** 購買
** 総務
** 財務
** 資源
left side
** 価値連鎖
*** 主活動
**** 購買物流
**** 製造
**** 出荷物流
**** マーケティング・販売
**** サービス
*** 支援活動
**** インフラストラクチャ
**** 人事・労務管理
**** 技術開発
**** 調達活動

@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* ドメイン

left side
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように

right side

** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== 業務領域(サブドメイン)

==== 中核の業務領域(コアサブドメイン)

==== 一般的な業務領域(汎用サブドメイン)

==== 補完的な業務領域(サポートサブドメイン)

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

