:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 印刷・広告制作会社A社の事例

== 与件

　A社は首都圏を拠点とする、資本金2,000 万円、従業員15 名の印刷・広告制作会社である。1960 年に家族経営の印刷会社として創業し、1990 年より長男が2 代目として引き継ぎ、30 年にわたって経営を担ってきたが、2020 年より3 代目が事業を承継している。

　創業時は事務用品の分野において、事務用品メーカーの印刷下請と特殊なビジネスフォームの印刷加工を主な業務としていた。当初は印刷工場を稼働しており、職人が手作業で活字を並べて文章にした版を作って塗料を塗る活版印刷が主流で、製版から印刷、加工までの各工程は、専門的な技能・技術によって支えられ、社内、社外の職人の分業によって行われてきた。

　しかしながら1970 年代からオフセット印刷機が普及し始めると、専門化された複数の工程を社内、社外で分業する体制が崩れ始め、それまで印刷職人の手作業によって行われてきた工程が大幅に省略され、大量・安価に印刷が仕上げられるようになった。

　さらに2000 年頃より情報通信技術の進化によって印刷のデジタル化が加速し、版の作成を必要としないオンデマンド機が普及することによって、オフィスや広告需要の多くが、より安価な小ロット印刷のサービスに置き換わっていった。とりわけ一般的な事務用印刷の分野においては、技術革新によって高度な専門的技術や知識が不要となったため、印刷業ではない他分野からの新規参入が容易になり、さらに印刷の単価が下がっていった。

　こうした一連の技術革新に伴う経営環境の変化に直面する中で、多くの印刷会社が新しい印刷機へと設備を刷新してきたのに対して、A 社では、2 代目が社長に就任すると、保有していた印刷機、印刷工場を順次売却し、印刷機を持たない事業へと転換した。制作物のデザイン、製版、印刷、製本までの工程を一括受注し、製版や印刷工程を、凸版、凹版、平版などの版式の違いに応じて専門特化された協力企業に依頼することで、外部にサプライチェーンのネットワークを構築し、顧客の細かいニーズに対応できるような分業体制を整えることに注力した。

　A 社では、割り付けやデザインと紙やインク、印圧などの仕様を決定して、印刷、製本、加飾などの各工程において協力企業を手配して指示することが主な業務となっていった。当時、新しい技術に置き換わりつつあった事務用印刷などの事業を大幅に縮小し、多工程にわたり高品質、高精度な印刷を必要とする美術印刷の分野にのみ需要を絞ることで、高度で手間のかかる小ロットの印刷、出版における事業を幅広く展開できるようになった。その結果、イベントや展示に用いられる紙媒体の印刷物、見本や写真、図録、画集、アルバムなどの高精度な仕上がりが求められる分野において需要を獲得していった。

　1990年代から行われた事業の転換は、長期にわたって組織内部のあり方も大きく変えていった。印刷機を社内で保有していた時は、製版を専門とする職人を抱えていたが、定年を迎えるごとに版下制作工程、印刷工程を縮小し、それらの工程は協力企業に依頼することとなった。そして、図案の作成と顧客との接点となるコンサルティングの工程のみを社内に残し、顧客と版下職人、印刷工場を仲介し、印刷の段取りを決定して協力企業に対して指示を出し、各工程間の調整を専門に行うディレクション業務へと特化していった。

　他方で2000年代に入ると、同社はデザインと印刷コンテンツのデジタル化に経営資源を投入し、とりわけ高精細画像のデータ化においてプログラミングの専門知識を持つ人材を採用し始めた。社内では、複数の事業案件に対してそれぞれプロジェクトチームを編成し、対応することとなった。具体的には、アートディレクターがプロジェクトを統括して事業の進捗を管理し、外部の協力企業を束ねる形で、制作工程を調整しディレクションする体制となった。

　また、広告代理店に勤務していた3 代目が加わると、2 代目は図案制作の工程を版下制作から独立させて、新たにデザイン部門を社内に発足させ、3 代目に部門の統括を任せた。3 代目は、前職においてデザイナー、アーティストとの共同プロジェクトに参画していた人脈を生かし、ウェブデザイナーを2 名採用した。こうした社内の人材の変化を受けて、紙媒体に依存しない分野にも事業を広げ、ウェブ制作、コンテンツ制作を通じて、地域内の中小企業が大半を占める既存の顧客に向けた広告制作へと業務を拡大した。しかしながら、新たな事業の案件を獲得していくことは難しかった。とりわけ、こうした新たな事業を既存の顧客に訴求するためには、新規の需要を創造していくことが求められた。また、中小企業向け広告制作の分野においては、既に数多くの競合他社が存在しているため、非常に厳しい競争環境であった。さらに新規の市場を開拓するための営業に資源を投入することも難しいために、印刷物を伴わない受注を増やしていくのに大いに苦労している。

　新規のデザイン部門と既存の印刷部門はともに、サプライチェーンの管理を担当し、デザインの一部と、製版、印刷、加工に至る全ての工程におけるオペレーションは外部に依存している。必要に応じて外部のフォトグラファーやイラストレーター、コピーライター、製版業者、印刷職人との協力関係を構築することで、事業案件に合わせてプロジェクトチームが社内に形成されるようになった。

　2代目経営者の事業変革によって、印刷部門5 名とデザイン部門10 名の2 部門体制で事業を行うようになり、正社員は15 名を保っている。3 代目は特に営業活動を行わず、主に初代、2 代目の経営者が開拓した地場的な市場を引き継ぎ、既存顧客からの紹介や口コミを通じて新たな顧客を取り込んできたが、売り上げにおいて目立った回復のないまま現在に至っている。

（令和3年度　中小企業診断士2次筆記試験　事例1　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startwbs

* A社
** 印刷部門
*** プロジェクトチーム
**** アートディレクター
**** ウェブデザイナー
** デザイン部門
*** プロジェクトチーム
**** アートディレクター
**** ウェブデザイナー

@endwbs
----

=== ビジネスモデル

[plantuml]
----
@startmindmap

* ビジネスモデル
-- 外部環境
--- 競争(XC)
---- とりわけ一般的な事務用印刷の分野においては、技術革新によって高度な専門的技術や知識が不要となったため、印刷業ではない他分野からの新規参入が容易になり、さらに印刷の単価が下がっていった
---- 一連の技術革新に伴う経営環境の変化に直面する中で、多くの印刷会社が新しい印刷機へと設備を刷新してきたのに対して、A 社では、2 代目が社長に就任すると、保有していた印刷機、印刷工場を順次売却し、印刷機を持たない事業へと転換した
---- 中小企業向け広告制作の分野においては、既に数多くの競合他社が存在しているため、非常に厳しい競争環境であった
--- 政治・社会・技術(XS)
---- 1970年代からオフセット印刷機が普及し始めると、専門化された複数の工程を社内、社外で分業する体制が崩れ始め、それまで印刷職人の手作業によって行われてきた工程が大幅に省略され、大量・安価に印刷が仕上げられるようになった
---- 2000年頃より情報通信技術の進化によって印刷のデジタル化が加速し、版の作成を必要としないオンデマンド機が普及することによって、オフィスや広告需要の多くが、より安価な小ロット印刷のサービスに置き換わっていった
--- マクロ経済(XE)
--- 市場(XM)
** 内部環境
*** 顧客
**** 顧客セグメント(CS)
***** イベントや展示に用いられる紙媒体の印刷物、見本や写真、図録、画集、アルバムなどの高精度な仕上がりが求められる分野において需要を獲得していった
***** 地域の中小企業が大半を占める既存の顧客に向けた広告制作へと業務を拡大した
***** 新たな事業の案件を獲得していくことは難しかった。とりわけ、こうした新たな事業を既存の顧客に訴求するためには、新規の需要を創造していくことが求められた
***** 3代目は特に営業活動を行わず、主に初代、2 代目の経営者が開拓した地場的な市場を引き継ぎ、既存顧客からの紹介や口コミを通じて新たな顧客を取り込んできたが、売り上げにおいて目立った回復のないまま現在に至っている
*** 価値
**** 価値提案(VP)
***** 創業時は事務用品の分野において、事務用品メーカーの印刷下請と特殊なビジネスフォームの印刷加工を主な業務としていた
***** 2代目が社長に就任すると、保有していた印刷機、印刷工場を順次売却し、印刷機を持たない事業へと転換した
***** 当時、新しい技術に置き換わりつつあった事務用印刷などの事業を大幅に縮小し、多工程にわたり高品質、高精度な印刷を必要とする美術印刷の分野にのみ需要を絞ることで、高度で手間のかかる小ロットの印刷、出版における事業を幅広く展開できるようになった
***** 紙媒体に依存しない分野にも事業を広げ、ウェブ制作、コンテンツ制作を通じて、地域内の中小企業が大半を占める既存の顧客に向けた広告制作へと業務を拡大した
**** チャネル(CH)
*** インフラ
**** 主要活動(KA)
***** 当初は印刷工場を稼働しており、職人が手作業で活字を並べて文章にした版を作って塗料を塗る活版印刷が主流で、製版から印刷、加工までの各工程は、専門的な技能・技術によって支えられ、社内、社外の職人の分業によって行われてきた
***** 製作物のデザイン、製版、印刷、製本までの工程を一括受注し、製版や印刷工程を、凸版、凹版、平版などの版式の違いに応じて専門特化された協力企業に依頼することで、外部にサプライチェーンのネットワークを構築し、顧客の細かいニーズに対応できるような分業体制を整えることに注力した
***** A社では、割り付けやデザインと紙やインク、印圧などの仕様を決定して、印刷、製本、加飾などの各工程において協力企業を手配して指示することが主な業務となっていった
***** 図案の作成と顧客との接点となるコンサルティングの工程のみを社内に残し、顧客と版下職人、印刷工場を仲介し、印刷の段取りを決定して協力企業に対して指示を出し、各工程間の調整を専門に行うディレクション業務へと特化していった
***** 社内では、複数の事業案件に対してそれぞれプロジェクトチームを編成し、対応することとなった。具体的には、アートディレクターがプロジェクトを統括して事業の進捗を管理し、外部の協力企業を束ねる形で、制作工程を調整しディレクションする体制となった
**** 主要リソース(KR)
***** 資本金2,000 万円、従業員15 名
***** 1960 年に家族経営の印刷会社として創業
***** 1990年代から行われた事業の転換は、長期にわたって組織内部のあり方も大きく変えていった
***** A社では、2代目が社長に就任すると、保有していた印刷機、印刷工場を順次売却し、印刷機を持たない事業へと転換した
***** 印刷機を社内で保有していた時は、製版を専門とする職人を抱えていたが、定年を迎えるごとに版下制作工程、印刷工程を縮小し、それらの工程は協力企業に依頼することとなった
***** 2000年代に入ると、同社はデザインと印刷コンテンツのデジタル化に経営資源を投入し、とりわけ高精細画像のデータ化においてプログラミングの専門知識を持つ人材を採用し始めた
***** 広告代理店に勤務していた3 代目が加わると、2 代目は図案制作の工程を版下制作から独立させて、新たにデザイン部門を社内に発足させ、3 代目に部門の統括を任せた
***** 3代目は、前職においてデザイナー、アーティストとの共同プロジェクトに参画していた人脈を生かし、ウェブデザイナーを2 名採用した
***** 新規の市場を開拓するための営業に資源を投入することも難しいために、印刷物を伴わない受注を増やしていくのに大いに苦労している
***** 新規のデザイン部門と既存の印刷部門はともに、サプライチェーンの管理を担当し、デザインの一部と、製版、印刷、加工に至る全ての工程におけるオペレーションは外部に依存している
***** 2代目経営者の事業変革によって、印刷部門5 名とデザイン部門10 名の2 部門体制で事業を行うようになり、正社員は15 名を保っている
**** 主要パートナー(KP)
***** 外部の協力企業
*** 資金
**** 収益源(R$)
**** コスト構造(C$)場

@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap

* SWOT
** 内部環境
***[#lightgreen] 強み
***[#yellow] 弱み
left side
** 外部環境
***[#lightblue] 機会
***[#red] 脅威

@endmindmap
----

=== VRIO分析

[plantuml]
----
@startmindmap

* VRIO
** 経済的価値
** 希少性
left side
** 模倣困難性
** 組織能力

@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap

* ドメイン
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように

@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap

* 成長戦略
** 既存市場
*** 市場浸透
*** 商品開発
** 新市場
*** 市場開発
*** 多角化
**** 水平的多角化
**** 垂直型多角化
**** 集中型多角化
**** 集成型多角化

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** ドメイン
right side
** 成長戦略

@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap

* 基本戦略
** コストリーダーシップ
** 差別化
** 集中

@endmindmap
----

==== 競争戦略

[plantuml]
----
@startmindmap

* 競争戦略
** リーダー
*** 市場拡大
*** 同質化
** チャレンジャー
*** 差別化
** ニッチャー
*** 集中
** フォロワー
*** 追随

@endmindmap
----

==== 価値連鎖

[plantuml]
----
@startmindmap

* 価値連鎖
** 主活動
*** 購買物流
*** 製造
*** 出荷物流
*** マーケティング・販売
*** サービス
** 支援活動
*** インフラストラクチャ
*** 人事・労務管理
*** 技術開発
*** 調達活動

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
left side
** 基本戦略
** 競争戦略
right side
** 価値連鎖

@endmindmap
----

=== 機能戦略

==== 販売

==== 生産

==== 購買

==== 総務

==== 財務

==== 資源

==== イシューツリー

[plantuml]
----
@startmindmap

* イシューツリー
** 販売
** 生産
** 購買
** 総務
** 財務
** 資源
left side
** 価値連鎖
*** 主活動
**** 購買物流
**** 製造
**** 出荷物流
**** マーケティング・販売
**** サービス
*** 支援活動
**** インフラストラクチャ
**** 人事・労務管理
**** 技術開発
**** 調達活動

@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* ドメイン

left side
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように

right side

** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== 業務領域(サブドメイン)

==== 中核の業務領域(コアサブドメイン)

==== 一般的な業務領域(汎用サブドメイン)

==== 補完的な業務領域(サポートサブドメイン)

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

