:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 事食肉と食肉加工品の製造・販売を行うB社の事例例

== 与件

　B社は資本金3,000 万円、従業者数は45 名（うちパート従業員21 名）で、食肉と食肉加工品の製造・販売を行う事業者である。現在の事業所は本社、工場、直営小売店1 店舗である。2021 年度の販売額は約9 億円で、取扱商品は牛肉・豚肉・鶏肉・食肉加工品である。

　B社はX県の大都市近郊に立地する。高速道路のインターチェンジからも近く、車の利便性は良いエリアだ。B 社の周辺には、大規模な田畑を所有する古くからの住民もいるが、工業団地があるため、現役世代が家族で居住する集合住宅も多い。

　1955年、B 社はこの地で牛肉、豚肉、鶏肉、肉の端材を使った揚げたてコロッケなどの総菜を販売する食肉小売店を開業した。当時の食肉消費拡大の波に乗って順調に売り上げを伸ばしたB 社は、1960 年代に入ると、食肉小売事業に加え、地域の百貨店や近隣のスーパーなどの大型小売業へ食肉を納入する事業を手がけるようになった。

　百貨店やスーパーを取引先としてきたこともあって、B 社の商品はクオリティの高さに定評がある。仕入れ元からのB 社に対する信頼も厚く、良い食肉を仕入れられる体制が整っている。B 社は、百貨店向けには贈答用を含めた最高級品質の食肉や食肉加工品の販売を行い、直営の食肉小売店では対面接客による買物客のニーズに合わせた販売を行い、スーパー向けには食卓で日常使いしやすいカット肉やスライス肉などの販売を行っており、さまざまな食肉の消費機会に対応できる事業者である。

　大型小売業の成長とともにB 社も成長していたが、1980 年代後半以降、スーパーは大手食肉卸売業者と取引を行うようになったため、B 社からスーパーへの納入量は徐々に減少していった。現在、B 社の周囲5 km 圏内には広大な駐車場を構える全国チェーンのスーパーが3 店舗あり、食肉も取り扱っているが、いずれもB 社との取引関係はない。

　こうした経営環境の変化を前に、B 社社長は、直営の食肉小売店での販売と百貨店やスーパーを主要取引先とする商売を続けていくことに危機を感じた。そこで1990年代に入ってすぐ、次に挙げる3 点で事業内容の見直しを行った。

　第1に、新たな取引先の開拓である。従来の百貨店やスーパーとの取引に加え、県内や隣接県のホテル・旅館、飲食店などに活路を見出した。B 社のあるX 県は、都市部と自然豊かな場所がともに存在し、高速道路で行き来できる。また、野菜・果物・畜産などの農業、漁業、機械や食品などの工業、大型ショッピングセンターなどの商業、観光サービス業がバランスよく発展している。山の幸、海の幸の特産品にも恵まれ、大規模な集客施設もあれば、四季それぞれに見どころのある観光エリアもあり、新たな取引先探しには事欠かなかった。

　第2に、自社工場を新設し、食肉加工品製造も行えるようにした。高い技術力を有する職人をB 社に招き入れ、良質でおいしい食肉加工品を製造できる体制を整えた。これによって、B 社は最高級のハムやソーセージ、ローストビーフなどの食肉加工品を自社ブランドで開発できるようになった。単品販売もできるうえ、詰め合わせれば贈答品にもなり、これら食肉加工品は直営小売店や高速道路の土産物店、道の駅などで販売している。また、取引先のニーズに応じて、相手先ブランドでの食肉加工品製造を請け負うことも可能になった。

　これと関連して第3 に、取引先へのコンサルテーションも手がけるようになった。自社工場設立以前、B 社は食肉販売を主な事業としていたため、取り扱う商品は標準的なカットやスライスを施した食肉であり、高度な加工を必要としなかった。しかし、ホテル・旅館や飲食店との取引の場合、販売先の調理の都合に合わせた形状のカットや、指定された個数でのパッキング、途中工程までの調理済み商品が求められるなど、顧客ニーズにきめ細かく合わせることが必要となってきた。B 社は自社工場という加工の場をもつことによって、個々の顧客の要望に応じた納品が可能になった。最近では、飲食店に対してメニュー提案を行ったり、その半加工を請け負ったりすることも増えている。

　事業見直しを進めた現在、B 社取引先の多くは1990 年代以降に開拓した事業者となった。2019 年度時点でのB 社の売上構成比は、卸売事業が9 割、直営小売事業が1 割である。折からのインバウンド需要の拡大を受け、ホテル・旅館との取引は絶好調であった。加えて2020 年夏には東京オリンピック・パラリンピックを控え、B 社はさらなる飛躍を期待し、冷凍在庫も積み増していた。

　ところが、国内での新型コロナウイルス感染症の発生を受け、ホテル・旅館や飲食店などを主要取引先とするB 社の経営は大打撃を受けた。B 社の2020 年度の売り上げは、2019 年度のおよそ半分となった。2021 年度の売り上げも2020 年度から多少回復がみられる程度だ。東京オリンピック・パラリンピックのために積み増した冷凍在庫をさばくため、B 社は大手ネットショッピングモールに出店し、焼肉用やステーキ用として冷凍肉の販売も試してみた。しかし、コロナ禍で同じことを考えた食肉販売業者は多く、B 社紹介ページはネット上で埋もれ、消費者の目にはほとんど留まらないようだった。B 社にとってせめてもの救いは、直営の食肉小売店であった。コロナ禍の巣ごもり需要拡大の影響で、開業以来、とくに何の手も打って来なかった食肉小売店での販売だけが急上昇した。料理の楽しさに目覚めた客や、作りたての揚げ物を買い求める客が、食肉専門店の魅力に気づいて足を運ぶようになった結果だった。

　B社社長はこの2年以上、コロナ禍で長期にわたって取引が激減しているホテル・旅館や、続々と閉店する飲食店を目の当たりにしてきた。もちろんB 社の販売先の多くはまだ残っているが、コロナ収束後、これらの事業者がすぐにコロナ前の水準で取引してくれるようになるとはとても思えずにいる。

　B社社長は高齢のため、同社専務を務める息子がまもなく事業を承継する予定だ。アフターコロナと事業承継を見据え、B 社社長は自社事業の再構築を行うべく、中小企業診断士に相談した。B 社はこのところ卸売事業を主軸としてきた。しかし、中小企業診断士との対話を重ねていくうち、B 社社長は自社の売り上げが他社の動向に左右されていることに気づき、今後はB 社自身が最終消費者と直接結びつく事業領域を強化すべきであると納得するに至った。B 社社長は、自社の強みを生かした新たな事業展開ができるよう、中小企業診断士にさらなる助言を求めた。

（令和4年度　中小企業診断士2次筆記試験　事例2　問題より引用）

== 環境分析

=== 組織図

[plantuml]
----
@startmindmap

* B 社
** 卸売事業
** 直営小売事業
*** 食肉小売店
*** 大手ネットショッピングモール課

@endmindmap
----

=== ビジネスモデル

[plantuml]
----
@startmindmap
* ビジネスモデル
-- 外部環境
--- 競争(XC)
---- 1980 年代後半以降、スーパーは大手食肉卸売業者と取引を行うようになったため、B 社からスーパーへの納入量は徐々に減少していった
--- 政治・社会・技術(XS)
---- B社のあるX 県は、都市部と自然豊かな場所がともに存在し、高速道路で行き来できる。また、野菜・果物・畜産などの農業、漁業、機械や食品などの工業、大型ショッピングセンターなどの商業、観光サービス業がバランスよく発展している
---- 山の幸、海の幸の特産品にも恵まれ、大規模な集客施設もあれば、四季それぞれに見どころのある観光エリアもあり、新たな取引先探しには事欠かなかった
---- 国内での新型コロナウイルス感染症の発生を受け、ホテル・旅館や飲食店などを主要取引先とするB 社の経営は大打撃を受けた
--- マクロ経済(XE)
---- コロナ禍で長期にわたって取引が激減しているホテル・旅館や、続々と閉店する飲食店を目の当たりにしてきた
--- 市場(XM)
** 内部環境
*** 顧客
**** 顧客セグメント(CS)
***** B社の周辺には、大規模な田畑を所有する古くからの住民もいるが、工業団地があるため、現役世代が家族で居住する集合住宅も多い
***** 従来の百貨店やスーパーとの取引に加え、県内や隣接県のホテル・旅館、飲食店などに活路を見出した
*** 価値
**** 価値提案(VP)
***** 食肉と食肉加工品の製造・販売
***** 1955年、牛肉、豚肉、鶏肉、肉の端材を使った揚げたてコロッケなどの総菜を販売する食肉小売店を開業
***** 百貨店やスーパーを取引先としてきたこともあって、B 社の商品はクオリティの高さに定評がある
***** B社は最高級のハムやソーセージ、ローストビーフなどの食肉加工品を自社ブランドで開発できるようになった
***** 飲食店に対してメニュー提案を行ったり、その半加工を請け負ったりすることも増えている
**** チャネル(CH)
***** 百貨店向けには贈答用を含めた最高級品質の食肉や食肉加工品の販売、直営の食肉小売店では対面接客による買物客のニーズに合わせた販売、スーパー向けには食卓で日常使いしやすいカット肉やスライス肉などの販売
***** 食肉加工品は直営小売店や高速道路の土産物店、道の駅などで販売
***** 取引先のニーズに応じて、相手先ブランドでの食肉加工品製造を請け負うことも可能
***** 大手ネットショッピングモールに出店し、焼肉用やステーキ用として冷凍肉の販売も試してみた
***** コロナ禍の巣ごもり需要拡大の影響で、開業以来、とくに何の手も打って来なかった食肉小売店での販売だけが急上昇した
*** インフラ
**** 主要活動(KA)
***** ホテル・旅館や飲食店との取引の場合、販売先の調理の都合に合わせた形状のカットや、指定された個数でのパッキング、途中工程までの調理済み商品が求められるなど、顧客ニーズにきめ細かく合わせることが必要となってきた。B 社は自社工場という加工の場をもつことによって、個々の顧客の要望に応じた納品が可能になった
**** 主要リソース(KR)
***** 仕入元からの信頼も厚く、良い食肉を仕入れられる体制が整っている
***** 自社工場を新設し、食肉加工品製造も行えるようにした。高い技術力を有する職人をB 社に招き入れ、良質でおいしい食肉加工品を製造できる体制を整えた
**** 主要パートナー(KP)
*** 資金
**** 収益源(R$)
***** 2019年度時点でのB 社の売上構成比は、卸売事業が9 割、直営小売事業が1 割である
**** コスト構造(C$)
@endmindmap
----

=== SWOT分析

[plantuml]
----
@startmindmap
* SWOT
-- 外部環境
--- 機会
--- 脅威
** 内部環境
*** 強み
*** 弱み
@endmindmap
----

== 事業分析

=== 企業戦略

==== ドメイン

[plantuml]
----
@startmindmap
* ドメイン
** 企業ドメイン
*** 理念
*** ビジョン
*** ミッション
** 事業ドメイン
*** 誰に
*** 何を
*** どのように
@endmindmap
----

==== 成長戦略

[plantuml]
----
@startmindmap
* 成長戦略
** 現状市場
*** 市場浸透
*** 市場開発
** 新規市場
*** 商品開発
*** 多角化
**** 水平的多角化
**** 垂直型多角化
**** 集中型多角化
**** 集成型多角化

@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap
* イシューツリー
** ドメイン
** 成長戦略
@endmindmap
----

=== 事業戦略

==== 基本戦略

[plantuml]
----
@startmindmap
* 基本戦略
** コストリーダーシップ
** 差別化
** 集中
@endmindmap
----

==== 価値連鎖

[plantuml]
----
@startmindmap
* 価値連鎖
** 主活動
*** 購買物流
*** 製造
*** 出荷物流
*** マーケティング・販売
*** サービス
** 支援活動
*** インフラストラクチャ
*** 人事・労務管理
*** 技術開発
*** 調達活動
@endmindmap
----

==== 競争地位別の戦略

[plantuml]
----
@startmindmap
* 競争地位別の戦略
** リーダー
*** 市場拡大
*** 同質化
** チャレンジャー
*** 差別化
** ニッチャー
*** 集中
** フォロワー
*** 追随
@endmindmap
----

==== イシューツリー

[plantuml]
----
@startmindmap
* イシューツリー
** 競争戦略
** 価値連鎖
** 基本戦略
@endmindmap
----

=== 機能戦略

==== 販売

==== 生産

==== 購買

==== 総務

==== 財務

==== 資源

==== イシューツリー

[plantuml]
----
@startmindmap
* イシューツリー
*** 販売
*** 生産
*** 購買
*** 総務
*** 財務
*** 資源
@endmindmap
----

== 業務分析

[plantuml]
----
@startmindmap

* A社
-- ドメイン
--- 企業ドメイン
---- 理念
---- ビジョン
---- ミッション
--- 事業ドメイン
---- 誰に
----- 事業者
---- 何を
---- どのように
** サブドメイン
*** コアサブドメイン
*** 汎用サブドメイン
*** サポートサブドメイン

@endmindmap
----


=== サブドメイン

==== コアサブドメイン

==== 汎用サブドメイン

==== サポートサブドメイン

=== ビジネスコンテキスト

=== ビジネスユースケース

==== 業務

===== ユースケース図

[plantuml]
----
@startuml

title ビジネスユースケース

@enduml
----

==== シーケンス図

[plantuml]
----
@startuml

title 業務シーケンス図

@enduml
----

==== 業務フロー図

===== 業務

[plantuml]
----
@startuml

title 業務フロー


@enduml
----

