:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 企業経営理論

== 経営戦略

=== 経営活動の全体像

[plantuml]
----
@startmindmap
* 経営活動の構成
left side
** 経営理念
*** 企業の存在意義、目的
**** 変わらない
*** 意義
**** モチベーション
**** 判断基準
**** コミュニケーションのベース
*** 留意点
**** 理念を組織文化に根付かせる
***** 価値観
***** 行動規範
** ビジョン
*** 企業の将来像
*** 目標
** 社是、社訓
*** 経営理念をキャッチコピー化したもの
** ミッション
*** 企業の使命
right side
** 経営戦略
*** 目標を実現するための手段
*** 目的
**** 環境適応
**** 競争優位の獲得
*** 種類
**** 企業戦略（成長戦略）
**** 事業戦略（競争戦略）
**** 機能戦略
** 経営計画
*** 具体的な計画
**** 責任者
**** 期限有り
*** 種類
**** 長期／中期／短期
***** 長期
****** 通常、5年以上
***** 中期
****** 通常、３年程度
***** 短期
****** 通常、１年
**** 総合／部門別
*** 計画の見直し
**** ローリングプラン
***** 定期的見直し
**** コンティンジェンシープラン
***** 不測事態の対応
****** 事業継続計画（BCP）
***** シャドープラン
**** 危機管理
***** 事業継続計画
****** 事業継続管理
*** 留意点
**** 分析麻痺症候群
***** 分析ばかりで実行されない
***** スタッフ部門と事業部門の壁
** コーポレートアイデンティティ
@endmindmap
----

=== 経営理念とビジョン

経営理念は、企業が存在する理由や目的を表します。これは社員のやる気を引き出す役割も果たします。経営理念は企業の基本的な考え方であり、すべての活動の基盤となります。

これに対して、ビジョンは企業が将来どうありたいかを表します。ビジョンは企業が目指す理想の姿や目標を示します。これは経営者が考える未来の企業像であり、方向性を社員や関係者に伝える役割を果たします。

経営理念とビジョンはどちらも企業経営にとって重要ですが、役割は異なります。経営理念は企業の存在意義を明確にし、社員のやる気を支える基盤です。一方、ビジョンは企業の将来像を示し、経営者の理想的な目標を表します。

=== 経営戦略

[plantuml]
----
@startwbs

* 企業戦略(成長戦略)
** 事業戦略(競争戦略)
*** 機能戦略
*** 機能戦略
*** 機能戦略
** 事業戦略(競争戦略)
*** 機能戦略
*** 機能戦略
*** 機能戦略

@endwbs
----


=== マネジメントサイクル

[plantuml]
----
@startmindmap
* マネジメントサイクル
** PDS
*** Plan
*** Do
*** See
** PDCA
*** Plan
*** Do
*** Check
*** Action
@endmindmap
----

==== PDSサイクル

[plantuml]
----
@startuml
state PDS {
    Plan -> Do
    Do --> See
    See --> Plan
}
@enduml
----

PDSサイクルは、計画 (Plan)、実行 (Do)、評価 (See) の3つのステップから成るサイクルです。

1. *Plan（計画）*::
- 目標を設定し、その目標を達成するための具体的な計画を立てます。
- 計画には目標達成のための戦略、手段、スケジュールが含まれます。

2. *Do（実行）*::
- 計画した内容を実行に移します。
- 実行の過程で進捗や問題点を確認しながら、計画通りに進めます。

3. *See（評価）*::
- 実行の結果を評価し、目標がどの程度達成されたかを確認します。
- 評価には成果の測定や課題の特定が含まれます。

==== PDCAサイクル

[plantuml]
----
@startuml
state PDCA {
    Plan -> Do
    Do --> Check
    Check --> Action
    Action -> Plan
}
@enduml
----

PDCAサイクルは、計画 (Plan)、実行 (Do)、確認 (Check)、改善 (Action) の4つのステップから成るサイクルです。

1. *Plan（計画）*::
- 目標を設定し、その目標を達成するための具体的な計画を立てます。
- 計画には目標達成のための戦略、手段、スケジュールが含まれます。

2. *Do（実行）*::
- 計画した内容を実行に移します。
- 実行の過程で進捗や問題点を確認しながら、計画通りに進めます。

3. *Check（確認）*::
- 実行の結果を確認し、計画通りに進んでいるか、目標が達成されているかを検証します。
- データの収集と分析によって現状を把握し、問題点を特定します。

4. *Action（改善）*::
- 確認した結果を基に、必要な改善策を講じます。
- 改善策を取り入れて次の計画に反映させ、再度サイクルを回します。

=== 経営戦略の基本

[plantuml]
----
@startmindmap
* 経営戦略の基本
left side
** 戦略策定プロセス
*** 環境分析
**** 現状の分析が前提
**** SWOT分析
***** 内部環境
****** 強み
******* Strength
****** 弱み
******* Weakness
****** 経営資源面
****** 機能別
***** 外部環境
****** 機会
******* Opportunity
****** 脅威
******* Threat
****** マクロ環境
****** ミクロ環境
*** 企業戦略
**** ドメイン
***** どこで戦うか
**** どの事業に投資するか
*** 事業戦略
**** 事業別にどのように戦うか
*** 機能戦略
**** 機能別の方針をどうするか
right side
** 戦略のポイント
*** 戦略のアプローチ
**** ポジショニングベース型
***** 外部環境への適応を重視
***** 有利なポジションを取る
**** リソースベース型
***** 内部の資源を重視
***** 資源ベースの戦略
*** 経営資源
**** 種類
***** 有形
****** ヒト、モノ、カネ
***** 無形
****** 技術力、知的財産、ノウハウ
****** ブランド、信用、顧客情報
**** 競争優位の要件
***** Value
****** 経済的価値
***** Rarity
****** 希少性
***** Inimitablity
****** 模倣困難性
***** Organization
****** 組織能力
**** 競争優位をもたらす経営資源
***** 経路依存性
***** 因果曖昧性
**** コアコンピタンス
***** 中核的能力
****** 顧客に価値を提供
****** 真似しにくい
****** 広く展開できる
**** ケイパビリティ
***** 組織的能力
****** スピード
****** 高品質
****** 顧客対応
**** 情報的経営資源
@endmindmap
----

==== ドメイン（Domain）

ドメインは、事業を行う領域を指し、「誰に」「何を」「どのように」提供するのかを定義します。企業は一般に多角化（複数の事業を展開）しているため、それぞれのドメインは次のように機能します：

* 企業ドメイン：
** 企業の経営理念やアイデンティティに基づいて、企業全体の活動範囲や事業領域を決定します。
** 企業の将来の方向性や経営理念を考慮し、展開する事業領域を絞り込む役割を果たします。
** 企業全体を包括する範囲を表します。複数の事業ドメインを含み、企業の戦う範囲（事業）を限定する助けになります。
* 事業ドメイン：
** 具体的な事業範囲や事業の見方を決めるもので、競争戦略の基本方針を提供します。
** 各事業単位の具体的な範囲を表し、個々の事業がどの領域で競争するかを決定します。

企業ドメインと事業ドメインは異なる概念ですが、どちらも企業経営において欠かせない役割を果たします。

== マーケティング

[plantuml]
----
@startmindmap

* マーケティングの4P
left side
** 製品
*** プロダクトミックス
**** 製品ライン
**** 製品アイテム
*** ブランド
**** 採用戦略
***** 製品ライン間の類似性
****** 同質
******* ファミリーブランド
******* ブランドプラスグレード
****** 異質
******* ダブルブランド
******* 個別ブランド
***** 標的市場の類似性
****** 同質
******* ファミリーブランド
******* ダブルブランド
****** 異質
******* ブランドプラスグレード
******* 個別ブランド
**** 基本戦略
***** 製品カテゴリー
****** 既存製品
******* ライン拡張
******* マルチブランド
****** 新製品
******* ブランド拡張
******* 新ブランド
***** ブランド名
****** 既存
******* ライン拡張
******* ブランド拡張
****** 新規
******* マルチブランド
******* 新ブランド
*** パッケージング
** 価格
*** 基本戦略
**** コスト志向
***** 原価+利益
***** コストプラス法
***** マークアップ法
**** 需要志向
***** 需要価格設定
***** 心理的価格設定
****** 名声価格
****** 端数価格
****** 慣習価格
***** 競争志向
****** 実勢価格設定
****** 入札価格設定
*** 新製品
**** 上澄吸収価格
**** 市場浸透価格
*** 製品ミックス
**** 抱き合わせ価格
**** プライスライニング
**** キャプティブ価格
right side
** チャネル
*** 長さ
**** 直接
**** 間接
*** 幅
**** 開放的
**** 選択的
**** 排他的
*** 垂直的マーケティングシステム
** プロモーション
*** 基本戦略
**** プッシュ戦略
***** 人的販売
***** 販売促進
****** 消費者向け
******* サンプル
******* プレミアム
******* ポイントカード
******* 会員カード
******* POP広告
******* カタログ
****** 流通業者向け
******* リベート
******* アローワンス
******* 販売店コンテスト
******* リテールサポート
**** プル戦略
***** 広告
****** マスコミ広告
******* 新聞
******* テレビ
******* ラジオ
******* 雑誌
****** インターネット広告
****** SP広告
******* ダイレクトメール
******* 屋外広告
***** パブリシティ
*** 応用マーケティング
**** 関係性マーケティング
***** CRM
****** 顧客ロイヤリティ
****** 顧客生涯価値
****** RFM分析
****** FSP
***** ワントゥーワンマーケティング
****** データベースマーケティング
****** マスカスタマイゼーション
***** ダイレクトマーケティング
****** テレマーケティング
****** インターネット
******* ネットショップ
******* ソーシャルメディア
**** サービスマーケティング
***** 品質向上
****** マニュアル化・教育訓練
****** 従業員満足度
***** 生産性向上
****** 需要の調整
******* 予約制
******* ピーク時以外の需要喚起
****** 供給の改善
******* 非正規者品
******* セルフサービス

@endmindmap
----
