:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 企業経営理論

== 経営戦略

=== 経営活動の全体像

[plantuml]
----
@startmindmap
* 経営活動の構成
left side
** 経営理念
*** 企業の存在意義、目的
**** 変わらない
*** 意義
**** モチベーション
**** 判断基準
**** コミュニケーションのベース
*** 留意点
**** 理念を組織文化に根付かせる
***** 価値観
***** 行動規範
** ビジョン
*** 企業の将来像
*** 目標
** 社是、社訓
*** 経営理念をキャッチコピー化したもの
** ミッション
*** 企業の使命
right side
** 経営戦略
*** 目標を実現するための手段
*** 目的
**** 環境適応
**** 競争優位の獲得
*** 種類
**** 企業戦略（成長戦略）
**** 事業戦略（競争戦略）
**** 機能戦略
** 経営計画
*** 具体的な計画
**** 責任者
**** 期限有り
*** 種類
**** 長期／中期／短期
***** 長期
****** 通常、5年以上
***** 中期
****** 通常、３年程度
***** 短期
****** 通常、１年
**** 総合／部門別
*** 計画の見直し
**** ローリングプラン
***** 定期的見直し
**** コンティンジェンシープラン
***** 不測事態の対応
****** 事業継続計画（BCP）
***** シャドープラン
**** 危機管理
***** 事業継続計画
****** 事業継続管理
*** 留意点
**** 分析麻痺症候群
***** 分析ばかりで実行されない
***** スタッフ部門と事業部門の壁
** コーポレートアイデンティティ
@endmindmap
----

=== 経営理念とビジョン

経営理念は、企業が存在する理由や目的を表します。これは社員のやる気を引き出す役割も果たします。経営理念は企業の基本的な考え方であり、すべての活動の基盤となります。

これに対して、ビジョンは企業が将来どうありたいかを表します。ビジョンは企業が目指す理想の姿や目標を示します。これは経営者が考える未来の企業像であり、方向性を社員や関係者に伝える役割を果たします。

経営理念とビジョンはどちらも企業経営にとって重要ですが、役割は異なります。経営理念は企業の存在意義を明確にし、社員のやる気を支える基盤です。一方、ビジョンは企業の将来像を示し、経営者の理想的な目標を表します。

=== 経営戦略

[plantuml]
----
@startwbs

* 企業戦略(成長戦略)
** 事業戦略(競争戦略)
*** 機能戦略
*** 機能戦略
*** 機能戦略
** 事業戦略(競争戦略)
*** 機能戦略
*** 機能戦略
*** 機能戦略

@endwbs
----


=== マネジメントサイクル

[plantuml]
----
@startmindmap
* マネジメントサイクル
** PDS
*** Plan
*** Do
*** See
** PDCA
*** Plan
*** Do
*** Check
*** Action
@endmindmap
----

==== PDSサイクル

[plantuml]
----
@startuml
state PDS {
    Plan -> Do
    Do --> See
    See --> Plan
}
@enduml
----

PDSサイクルは、計画 (Plan)、実行 (Do)、評価 (See) の3つのステップから成るサイクルです。

1. *Plan（計画）*::
- 目標を設定し、その目標を達成するための具体的な計画を立てます。
- 計画には目標達成のための戦略、手段、スケジュールが含まれます。

2. *Do（実行）*::
- 計画した内容を実行に移します。
- 実行の過程で進捗や問題点を確認しながら、計画通りに進めます。

3. *See（評価）*::
- 実行の結果を評価し、目標がどの程度達成されたかを確認します。
- 評価には成果の測定や課題の特定が含まれます。

==== PDCAサイクル

[plantuml]
----
@startuml
state PDCA {
    Plan -> Do
    Do --> Check
    Check --> Action
    Action -> Plan
}
@enduml
----

PDCAサイクルは、計画 (Plan)、実行 (Do)、確認 (Check)、改善 (Action) の4つのステップから成るサイクルです。

1. *Plan（計画）*::
- 目標を設定し、その目標を達成するための具体的な計画を立てます。
- 計画には目標達成のための戦略、手段、スケジュールが含まれます。

2. *Do（実行）*::
- 計画した内容を実行に移します。
- 実行の過程で進捗や問題点を確認しながら、計画通りに進めます。

3. *Check（確認）*::
- 実行の結果を確認し、計画通りに進んでいるか、目標が達成されているかを検証します。
- データの収集と分析によって現状を把握し、問題点を特定します。

4. *Action（改善）*::
- 確認した結果を基に、必要な改善策を講じます。
- 改善策を取り入れて次の計画に反映させ、再度サイクルを回します。

=== 経営戦略の基本

[plantuml]
----
@startmindmap
* 経営戦略の基本
left side
** 戦略策定プロセス
*** 環境分析
**** 現状の分析が前提
**** SWOT分析
***** 内部環境
****** 強み
******* Strength
****** 弱み
******* Weakness
****** 経営資源面
****** 機能別
***** 外部環境
****** 機会
******* Opportunity
****** 脅威
******* Threat
****** マクロ環境
****** ミクロ環境
*** 企業戦略
**** ドメイン
***** どこで戦うか
**** どの事業に投資するか
*** 事業戦略
**** 事業別にどのように戦うか
*** 機能戦略
**** 機能別の方針をどうするか
right side
** 戦略のポイント
*** 戦略のアプローチ
**** ポジショニングベース型
***** 外部環境への適応を重視
***** 有利なポジションを取る
**** リソースベース型
***** 内部の資源を重視
***** 資源ベースの戦略
*** 経営資源
**** 種類
***** 有形
****** ヒト、モノ、カネ
***** 無形
****** 技術力、知的財産、ノウハウ
****** ブランド、信用、顧客情報
**** 競争優位の要件
***** Value
****** 経済的価値
***** Rarity
****** 希少性
***** Inimitablity
****** 模倣困難性
***** Organization
****** 組織能力
**** 競争優位をもたらす経営資源
***** 経路依存性
***** 因果曖昧性
**** コアコンピタンス
***** 中核的能力
****** 顧客に価値を提供
****** 真似しにくい
****** 広く展開できる
**** ケイパビリティ
***** 組織的能力
****** スピード
****** 高品質
****** 顧客対応
**** 情報的経営資源
@endmindmap
----

==== ドメイン（Domain）

ドメインは、事業を行う領域を指し、「誰に」「何を」「どのように」提供するのかを定義します。企業は一般に多角化（複数の事業を展開）しているため、それぞれのドメインは次のように機能します：

* 企業ドメイン：
** 企業の経営理念やアイデンティティに基づいて、企業全体の活動範囲や事業領域を決定します。
** 企業の将来の方向性や経営理念を考慮し、展開する事業領域を絞り込む役割を果たします。
** 企業全体を包括する範囲を表します。複数の事業ドメインを含み、企業の戦う範囲（事業）を限定する助けになります。
* 事業ドメイン：
** 具体的な事業範囲や事業の見方を決めるもので、競争戦略の基本方針を提供します。
** 各事業単位の具体的な範囲を表し、個々の事業がどの領域で競争するかを決定します。

企業ドメインと事業ドメインは異なる概念ですが、どちらも企業経営において欠かせない役割を果たします。

=== 企業戦略

[plantuml]
----
@startmindmap
* 企業戦略
left side
** ドメイン
*** 事業領域
**** 誰に何を・どのように
**** 目的
***** 意思決定の焦点
***** 資源を集中
***** 組織の一体化
*** ポイント
**** 分散を回避
***** 広すぎると競争激化
**** 適度の集中の回避
***** 狭すぎると事業不成立
*** 種類
**** 企業ドメイン
**** 事業ドメイン
*** 定義方法
**** 物理的
***** モノとして定義
***** 欠点
****** マーケティング・マイオペア（近視眼）
**** 機能的
***** コトとして定義
****** 顧客視点
***** 利点
****** 発展的
***** 欠点
****** 抽象的
*** 切り口
**** 市場・顧客軸
**** 機能軸
**** 技術軸
*** ドメインの転換
**** 環境変化に適応
right side
** 多角化戦略
*** （アンゾフ）成長ベクトル
**** 事業の方向性
*** 多角化の理由
**** 外部誘因
***** 新事業分野の開拓
***** リスク分散
**** 内部誘因
***** 組織スラックの活用
****** 余剰資産
***** シナジーの追求
****** 範囲の経済
******* コスト有利
****** 相乗効果
*** 多角化の効果
**** 相乗効果
***** ノウハウや技術等を同時に多重利用
**** 相補効果
***** 経営資源を補い合う
*** 多角化の分類
**** 関連型多角化
***** シナジー効果
**** 非関連型多角化
***** 事業間の関連性が希薄
***** 相補（コンプリメント）効果
**** 水平型多角化
**** 垂直型多角化
**** 集中型多角化
**** 集成型多角化
**** アンゾフの多角化戦略
**** ルメルトの多角化戦略
*** プロダクトポートフォリオ・マネジメント
**** 複数事業の管理
***** 戦略事業単位（SBU)
**** 前提
***** 経験曲線効果
****** 累計生産量（＋）→コスト（ー）
****** シェアが高い企業がコスト有利
***** 製品ライフサイクル
****** 導入期
******* 売上（低）、CF（ー）
****** 成長期
******* 売上（増）、CF(ーから＋へ）
****** 成熟期
******* 売上（安定）、CF(＋）
****** 衰退期
******* 売上（減）、CF（低）
**** 問題点
***** 財務の視点のみ
***** 過去の分析中心
***** 負け犬のモラール低下
***** シナジー無視
**** 改善版
***** ビジネススクリーン
****** 競争地位
****** 産業魅力度
**** 相対市場シェア
*** M&A
**** 統合の方法
***** 水平統合
***** 垂直統合
***** 多角化
**** 形態
***** 経営権移転なし
****** 提携
****** 合弁
***** 経営移転あり
****** 買収
****** 合併
**** 手法
***** TOB
****** 株式公開買い付け
***** MBO
****** 現経営陣による買収
***** MBI
****** 外部経営陣による買収
***** LBO
****** 企業を担保に買収資金調達
**** 効果
***** メリット
****** スピード
****** 弱みの補強
***** デメリット
****** 企業評価が難しい
****** 組織統合難しい
**** 分類
***** 友好的
***** 敵対的
****** 経営陣から見て
**** 買収防衛策
***** ポイズンビル
****** 財務悪化策
***** クラウンジュエル
****** 魅力的な事業を売却
***** ゴールデンパラシュート
****** 取締役の高額退職金
***** ホワイトナイト
****** 友好的買収者
** 事業再構築
*** アウトソーシング
**** コスト削減
**** 経営資源の集中
**** 外部の専門性活用
*** リストラクチャリング
**** 事業構造の再構築
*** リエンジニアリング
**** BPR
***** 業務プロセスの見直し
** 規模の経済性
@endmindmap
----

=== 事業戦略

[plantuml]
----
@startmindmap
* 事業戦略
left side
** 業界構造増分析
*** 5つの競争要因
**** ポーター
**** 収益性を決定
*** 競争環境
**** 競争業者
***** 既存業者の敵対関係
****** 競合他社が多い
******* 規模が同等
****** 成長率が低い
****** 差別化ができていない
****** 固定費が高い
**** 買い手
***** 買い手の交渉力
****** 強力な買い手
****** 製品が差別化されていない
**** 売り手
***** 売り手の交渉力
****** 売り手が少数で支配
****** 独自の製品・技術
**** 新規参入者
***** 新規参入の脅威
****** 参入障壁
******* 技術
******* 設備投資
******** 規模の経済
******* チャネル
**** 代替品
***** 代替品の脅威
**** 業界
***** 戦略グループ
****** 同じような戦略の企業
****** 同じ業界内
***** 移動障壁
****** 戦略グループ間の移動
right side
** 競争優位の戦略
*** ３つの基本戦略
**** コストリーダーシップ
***** 手段
****** 規模の経済性
****** 経験曲線効果
***** リスク
****** 価格競争
****** ニーズ変化
**** 差別化
***** 手段
****** 製品
****** サービス
****** ブランド
***** リスク
****** 価格差
****** 陳腐化
**** 集中
***** コスト集中
***** 差別化集中
***** リスク
****** 事業不成立
****** セグメントがあいまい
*** 価値連鎖
**** 利益
***** 付加価値を高める
***** コストを下げる
**** 価値活動
***** 全体最適
*** 競争地位別の戦略
**** リーダー
***** 市場拡大
****** フルライン
***** 同質化
**** チャレンジャー
***** 差別化
**** ニッチャー
***** 集中
****** ミニリーダー政策
**** フォロワー
***** 追随
@endmindmap
----

=== 技術戦略(MOT)

[plantuml]
----
@startmindmap
* 技術戦略（MOT）
left side
** イノベーション
*** 革新
**** プロダクト・イノベーション
***** 製品
**** プロセス・イノベーション
***** 生産工程
*** ライフサイクル
**** S字カーブ
***** １不確実
***** ２拡大
***** ３成熟
**** 不連続性
***** 新技術
*** 種類
**** 持続的
***** インクリメンタル
***** 改良
****** 主流顧客向け
**** 破壊的
***** ラディカル
***** 新しい価値
****** 新規顧客
*** イノベーションのジレンマ
**** リーダー企業
***** 破壊者に対応できない
***** 主要顧客の要望
*** オープンイノベーション
** 製品アーキテクチャ
*** 種類
**** インテグラル型
***** すり合わせ
***** 利点
****** 全体最適
****** 模倣困難
***** 欠点
****** 進化に時間
****** 調整コスト
**** モジュール型
***** 組合わせ
****** インターフェース
***** 利点
****** 多様な組み合わせ
****** 調整コスト削減
***** 欠点
****** 無駄が多い
****** I/Fの進化に時間
***** オープンアーキテクチャ戦略
*** デファクトスタンダード
**** 事実上の業界標準
***** ⇔デジュリ（公的）
**** ネットワーク外部性
***** メンバー（＋）⇔効用（＋）
right side
** ベンチャー企業
*** 成長過程
**** シード期
**** スタートアップ期
**** 急成長期
**** 安定成長期
*** 課題
**** 魔の川
***** 社会的有用性が識別困難
**** 死の谷
***** 商品化前に転落
**** ダーウィンの海
***** 競争による淘汰
*** Jカーブ効果（Jカーブ曲線）
**** キャッシュフロー
**** 時間
** 社内ベンチャー
*** 目的
**** 新規事業
**** チャレンジ精神
**** 既存資産の有効活用
*** メリット
**** 経営資源の活用
**** ブランド力・信用を活かす
**** リスクを抑える
*** デメリット
**** 組織的な承認が必要
**** 既存事業の制限
@endmindmap
----

== 経営組織

== マーケティング

[plantuml]
----
@startmindmap

* マーケティングの4P
left side
** 製品
*** プロダクトミックス
**** 製品ライン
**** 製品アイテム
*** ブランド
**** 採用戦略
***** 製品ライン間の類似性
****** 同質
******* ファミリーブランド
******* ブランドプラスグレード
****** 異質
******* ダブルブランド
******* 個別ブランド
***** 標的市場の類似性
****** 同質
******* ファミリーブランド
******* ダブルブランド
****** 異質
******* ブランドプラスグレード
******* 個別ブランド
**** 基本戦略
***** 製品カテゴリー
****** 既存製品
******* ライン拡張
******* マルチブランド
****** 新製品
******* ブランド拡張
******* 新ブランド
***** ブランド名
****** 既存
******* ライン拡張
******* ブランド拡張
****** 新規
******* マルチブランド
******* 新ブランド
*** パッケージング
** 価格
*** 基本戦略
**** コスト志向
***** 原価+利益
***** コストプラス法
***** マークアップ法
**** 需要志向
***** 需要価格設定
***** 心理的価格設定
****** 名声価格
****** 端数価格
****** 慣習価格
***** 競争志向
****** 実勢価格設定
****** 入札価格設定
*** 新製品
**** 上澄吸収価格
**** 市場浸透価格
*** 製品ミックス
**** 抱き合わせ価格
**** プライスライニング
**** キャプティブ価格
right side
** チャネル
*** 長さ
**** 直接
**** 間接
*** 幅
**** 開放的
**** 選択的
**** 排他的
*** 垂直的マーケティングシステム
** プロモーション
*** 基本戦略
**** プッシュ戦略
***** 人的販売
***** 販売促進
****** 消費者向け
******* サンプル
******* プレミアム
******* ポイントカード
******* 会員カード
******* POP広告
******* カタログ
****** 流通業者向け
******* リベート
******* アローワンス
******* 販売店コンテスト
******* リテールサポート
**** プル戦略
***** 広告
****** マスコミ広告
******* 新聞
******* テレビ
******* ラジオ
******* 雑誌
****** インターネット広告
****** SP広告
******* ダイレクトメール
******* 屋外広告
***** パブリシティ
*** 応用マーケティング
**** 関係性マーケティング
***** CRM
****** 顧客ロイヤリティ
****** 顧客生涯価値
****** RFM分析
****** FSP
***** ワントゥーワンマーケティング
****** データベースマーケティング
****** マスカスタマイゼーション
***** ダイレクトマーケティング
****** テレマーケティング
****** インターネット
******* ネットショップ
******* ソーシャルメディア
**** サービスマーケティング
***** 品質向上
****** マニュアル化・教育訓練
****** 従業員満足度
***** 生産性向上
****** 需要の調整
******* 予約制
******* ピーク時以外の需要喚起
****** 供給の改善
******* 非正規者品
******* セルフサービス

@endmindmap
----
