:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= ビジネスアーキテクチャ

== 全体像

[plantuml]
----
@startmindmap

* ビジネスアーキテクチャ
** ビジネスアーキテクチャとは
** ビジネスアーキテクチャを構成する主要な要素
*** プリンシプル
**** ガイディングプリンシプル
***** ビジネスアーキテクチャ
***** アプリケーションアーキテクチャ
***** データアーキテクチャ
***** テクノロジーアーキテクチャ
**** ビジネスプリンシプル
*** ビジネスモデル
**** ビジネスモデルキャンバス
** ビジネスケイパビリティとは
*** ビジネスケイパビリティモデル
**** ビジネスケイパビリティマップ
**** トップダウンアプローチ
**** ボトムアップアプローチ
*** ビジネスケイパビリティとビジネスモデルの対応
**** 階層化
**** レベリング
**** ヒートマッピング
** バリューストリーム
*** バリュー（価値）とは
*** バリューの分析
*** バリューチェーン
*** バリューチェーンとバリューストリームの違い
*** ケイパビリティをバリューストリームのステージにマッピングする
*** バリューストリームとビジネスケイパビリティモデルの作成順序について
** 組織マップ
** 情報マップ
** ビジネスシナリオ
*** ビジネスシナリオの作成方法
*** ビジネスシナリオワークショップ
** ビジネスアーキテクチャの検討例
*** ステップ1：ビジネスモデルキャンバスの活用
*** ステップ2：バリューストリームの作成
*** ステップ3：ケイパビリティの識別とマッピング
*** ステップ4：アプリケーションアーキテクチャとデータアーキテクチャの設計

@endmindmap
----

== ビジネスアーキテクチャとは

> ビジネスアーキテクチャとは、エンタープライズがどのように価値を生み出し、それを顧客に提供するかの構造を表現するもの

== ビジネスアーキテクチャを構成する主要な要素

=== プリンシプル

「プリンシプル」とは、原理原則という意味です。

それぞれの人が異なる立場や文化背景から考え方の違いを生じることがあります。そこで、プリンシプルはこのような場合に、考え方を統一するためのものとなります。

==== ガイディングプリンシプル

エンタープライズのビジョン、ミッション、価値観に基づいた基本的な方針や原則

==== ビジネスプリンシプル

ビジネスにおける原則原理を定義するもの

=== ビジネスモデル

組織が価値を創造し、提供し、そして獲得する方法を体系的に説明するもの

==== ビジネスモデルキャンバス

ビジネスモデルのスケッチを作成するための直観的な技法

== ビジネスケイパビリティとは

ビジネスが「何か」を行う能力

=== ビジネスケイパビリティモデル

特定のビジネスや組織が持つ能力

[plantuml]
----
@startmindmap

* ビジネスケイパビリティマップ
left side
** 戦略
*** ビジネスプラン
*** マーケティング
*** サプライヤ管理
*** 出店計画
*** 開発管理
*** アライアンス
right side
** コア
*** 生産管理
*** 製品管理
*** 配送管理
*** 販売管理
*** 店舗管理
*** 購買
** サポート
*** 財務管理
*** 教育管理
*** 資材管理
*** 人事管理
*** ヘルプデスク
*** 調達管理

@endmindmap
----

=== ビジネスケイパビリティとビジネスモデルの対応

==== 階層化

ビジネスケイパビリティを上位層、中間層、下位層の３つのカテゴリに分けるプロセス

==== レベリング

上位レベルのビジネスケイパビリティをより詳細に伝達するために、より下位のレベル（聴衆またはステークホルダにとって適切なレベル）に分解

==== ヒートマッピング

[plantuml]
----
@startmindmap

* ビジネスケイパビリティマップ
left side
** 戦略
***[#limegreen] ビジネスプラン
***[#limegreen] マーケティング
***[#limegreen] サプライヤ管理
***[#limegreen] 出店計画
***[#yellow] 開発管理
***[#red] アライアンス
right side
** コア
***[#yellow] 生産管理
***[#limegreen] 製品管理
***[#yellow] 配送管理
***[#limegreen] 販売管理
***[#limegreen] 店舗管理
***[#limegreen] 購買
** サポート
***[#yellow] 財務管理
***[#limegreen] 教育管理
***[#limegreen] 資材管理
***[#limegreen] 人事管理
***[#orange] ヘルプデスク
***[#limegreen] 調達管理
@endmindmap
----

* グリーン：成熟度高
* イエロー：成熟度中
* レッド：成熟度低
* オレンジ：新規に必要


== バリューストリーム

== 組織マップ

== 情報マップ

== ビジネスシナリオ

== ビジネスアーキテクチャの検討例
